#!/usr/bin/env node
// AUTO-GENERATED by Holdpoint — do not edit. Re-generate: npx holdpoint update
import { execSync, spawn } from "node:child_process";
import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { isAbsolute, join, relative, resolve } from "node:path";

const STOP_COMMAND = "node_modules/.bin/holdpoint check --staged";
const LIVE_COMMAND = "node_modules/.bin/holdpoint";
const LIVE_ARGS = ["event", "--engine", "codex", "--from-hook"];
const MAX_CONTEXT_CHARS = 100_000;
const MAX_CHECK_OUTPUT_CHARS = 60_000;
const CHECK_MAX_BUFFER_BYTES = 1024 * 1024 * 10;

const root = (() => {
  try {
    return execSync("git rev-parse --show-toplevel", {
      encoding: "utf8",
      stdio: ["ignore", "pipe", "ignore"],
    }).trim();
  } catch {
    return process.cwd();
  }
})();

// Codex sends a JSON object on stdin for every hook event.
let input = {};
try {
  const raw = readFileSync(0 /* stdin fd */, "utf8").trim();
  if (raw) input = JSON.parse(raw);
} catch { /* non-JSON or empty stdin — default to Stop behaviour */ }

function hookEventName() {
  return typeof input.hook_event_name === "string" ? input.hook_event_name : "Stop";
}

function truncateText(value, maxChars) {
  const text = String(value || "");
  if (text.length <= maxChars) return { text, truncated: false, originalLength: text.length };
  return {
    text: text.slice(0, maxChars) + "\n\n[Holdpoint output truncated to " + maxChars + " chars.]",
    truncated: true,
    originalLength: text.length,
  };
}

function isPathInsideRoot(repoRoot, absPath) {
  const rel = relative(repoRoot, absPath);
  return rel === "" || (!rel.startsWith("..") && !isAbsolute(rel));
}

function sendLiveEvent(payload) {
  try {
    const child = spawn(LIVE_COMMAND, LIVE_ARGS, {
      cwd: root,
      stdio: ["pipe", "ignore", "ignore"],
      detached: true,
    });
    child.stdin.end(JSON.stringify(payload));
    child.unref();
  } catch {
    // Live telemetry is best-effort and must never break Codex's hook flow.
  }
}

function readSessionContext() {
  const configPath = join(root, ".github/holdpoint/generated/checks.immutable.json");
  if (!existsSync(configPath)) return undefined;
  try {
    const cfg = JSON.parse(readFileSync(configPath, "utf8"));
    const files = Array.isArray(cfg.session_context_files) ? cfg.session_context_files : [];
    const parts = [];
    for (const file of files) {
      if (typeof file !== "string" || !file.trim()) continue;
      const abs = resolve(root, file);
      if (!isPathInsideRoot(root, abs) || !existsSync(abs)) continue;
      try { parts.push(`<!-- ${file} -->\n${readFileSync(abs, "utf8")}`); } catch {}
    }
    if (parts.length === 0) return undefined;
    const context = truncateText(parts.join("\n\n"), MAX_CONTEXT_CHARS);
    return {
      additionalContext: context.text,
      truncated: context.truncated,
      originalLength: context.originalLength,
      emittedLength: context.text.length,
    };
  } catch {
    return undefined;
  }
}

function outputAdditionalContext(eventName, context) {
  if (!context?.additionalContext) return;
  writeFileSync(1, JSON.stringify({
    hookSpecificOutput: {
      hookEventName: eventName,
      additionalContext: context.additionalContext,
    },
  }));
}

function runHoldpointChecks() {
  const startedAt = Date.now();
  try {
    // stdio: "pipe" — CLI output must NOT reach hook stdout as plain text.
    const output = execSync(STOP_COMMAND, {
      cwd: root,
      stdio: "pipe",
      encoding: "utf8",
      maxBuffer: CHECK_MAX_BUFFER_BYTES,
    });
    return {
      ok: true,
      durationMs: Date.now() - startedAt,
      output: String(output || "").trim(),
    };
  } catch (err) {
    const output = [err.stdout, err.stderr, err.message].filter(Boolean).join("\n").trim();
    const truncated = truncateText(output, MAX_CHECK_OUTPUT_CHARS);
    return {
      ok: false,
      durationMs: Date.now() - startedAt,
      output: truncated.text || "Holdpoint checks failed. Fix the issues above, then re-attempt.",
      truncated: truncated.truncated,
      originalLength: truncated.originalLength,
    };
  }
}

// ── SessionStart: inject session_context_files as additionalContext ────────────
const eventName = hookEventName();

if (eventName === "SessionStart" || eventName === "SubagentStart") {
  const context = readSessionContext();
  sendLiveEvent({
    ...input,
    holdpoint_context: context
      ? { truncated: context.truncated, originalLength: context.originalLength, emittedLength: context.emittedLength }
      : undefined,
  });
  outputAdditionalContext(eventName, context);
  process.exit(0);
}

// ── UserPromptSubmit: inject current datetime as additionalContext ─────────────
if (eventName === "UserPromptSubmit") {
  sendLiveEvent(input);
  const now = new Date();
  const datetimeContext =
    "Current date and time: " + now.toISOString() + " (UTC)\n" +
    "Provided by Holdpoint — use this to avoid knowledge-cutoff confusion.";
  outputAdditionalContext(eventName, { additionalContext: datetimeContext });
  process.exit(0);
}

// ── Stop: run checks, exit 0 (pass) or exit 2 (continue with feedback) ─────────
if (eventName === "Stop" || eventName === "SubagentStop") {
  if (input.stop_hook_active === true) {
    sendLiveEvent({ ...input, holdpoint_check: { skipped: true, reason: "stop_hook_active" } });
    process.exit(0);
  }
  const result = runHoldpointChecks();
  sendLiveEvent({ ...input, holdpoint_check: result });
  if (result.ok) {
    process.exit(0);
  }
  // Write captured check output to stderr — Codex uses this as the continuation prompt.
  process.stderr.write(
    result.output + "\n\nHoldpoint checks failed. Fix the issues above, then re-attempt.\n",
  );
  process.exit(2);
}

// Other hook events are telemetry-only. Do not emit pass-through allow decisions:
// PermissionRequest allow would auto-approve escalations, and PreToolUse allow
// has rewrite semantics in Codex. Empty stdout means "no decision".
sendLiveEvent(input);
process.exit(0);
