#!/usr/bin/env node
// AUTO-GENERATED by Holdpoint — do not edit. Re-generate: npx holdpoint update
import { execSync } from "node:child_process";
import { existsSync, readFileSync } from "node:fs";
import { join, resolve, sep } from "node:path";

const root = (() => {
  try {
    return execSync("git rev-parse --show-toplevel", { encoding: "utf8" }).trim();
  } catch {
    return process.cwd();
  }
})();

// Codex sends a JSON object on stdin for every hook event.
let input = {};
try {
  const raw = readFileSync(0 /* stdin fd */, "utf8").trim();
  if (raw) input = JSON.parse(raw);
} catch { /* non-JSON or empty stdin — default to Stop behaviour */ }

// ── SessionStart: inject session_context_files as additionalContext ────────────
if (input.hook_event_name === "SessionStart") {
  const configPath = join(root, ".github/holdpoint/generated/checks.immutable.json");
  if (!existsSync(configPath)) process.exit(0);
  try {
    const cfg = JSON.parse(readFileSync(configPath, "utf8"));
    const files = Array.isArray(cfg.session_context_files) ? cfg.session_context_files : [];
    const parts = [];
    for (const file of files) {
      if (typeof file !== "string" || !file.trim()) continue;
      const abs = resolve(root, file);
      if (!abs.startsWith(root + sep) && abs !== root) continue;
      if (!existsSync(abs)) continue;
      try { parts.push(`<!-- ${file} -->\n${readFileSync(abs, "utf8")}`); } catch {}
    }
    if (parts.length > 0) {
      // Codex SessionStart spec: JSON with hookSpecificOutput.additionalContext
      process.stdout.write(JSON.stringify({
        hookSpecificOutput: {
          hookEventName: "SessionStart",
          additionalContext: parts.join("\n\n"),
        },
      }));
    }
  } catch {}
  process.exit(0);
}

// ── Stop: run checks, exit 0 (pass) or exit 2 (continue with feedback) ─────────
try {
  // stdio: "pipe" — CLI output must NOT reach hook stdout as plain text.
  // Codex Stop spec: "plain text output is invalid for this event."
  const output = execSync("node_modules/.bin/holdpoint check --staged", {
    cwd: root,
    stdio: "pipe",
    encoding: "utf8",
  });
  void output; // success — exit 0 with no stdout
  process.exit(0);
} catch (err) {
  // Write captured check output to stderr — Codex uses this as the continuation prompt.
  const output = [err.stdout, err.stderr].filter(Boolean).join("\n").trim();
  process.stderr.write(
    (output ? output + "\n\n" : "") +
      "Holdpoint checks failed. Fix the issues above, then re-attempt.\n",
  );
  process.exit(2);
}
