#!/usr/bin/env node
// AUTO-GENERATED by Holdpoint — do not edit. Re-generate: npx holdpoint update
import { execSync } from "node:child_process";

const root = (() => {
  try {
    return execSync("git rev-parse --show-toplevel", { encoding: "utf8" }).trim();
  } catch {
    return process.cwd();
  }
})();

try {
  execSync("npx holdpoint@alpha check --staged", {
    cwd: root,
    stdio: "inherit",
    encoding: "utf8",
  });
  process.exit(0);
} catch (err) {
  // Capture any output that wasn't already written to stdout/stderr via inherit
  const extra = [err.stdout, err.stderr].filter(Boolean).join("\n").trim();
  process.stderr.write(
    (extra ? extra + "\n\n" : "") +
      "Holdpoint checks failed. Fix the issues above, then re-attempt.\n",
  );
  process.exit(2);
}
