#!/usr/bin/env node
// AUTO-GENERATED by Holdpoint — do not edit. Re-generate: npx holdpoint update
import { execSync } from "node:child_process";
import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { isAbsolute, join, relative, resolve } from "node:path";

const CHECK_COMMAND = "node_modules/.bin/holdpoint check --staged";
const LIVE_COMMAND = "node_modules/.bin/holdpoint event --engine cursor --from-hook";
const MAX_CONTEXT_CHARS = 100_000;
const MAX_CHECK_OUTPUT_CHARS = 60_000;
const CHECK_MAX_BUFFER_BYTES = 1024 * 1024 * 10;

function readInput() {
  try {
    const raw = readFileSync(0, "utf8").trim();
    return raw ? JSON.parse(raw) : {};
  } catch {
    return {};
  }
}

function resolveRepoRoot(cwd = process.cwd()) {
  try {
    return execSync("git rev-parse --show-toplevel", {
      cwd,
      encoding: "utf8",
      stdio: ["pipe", "pipe", "ignore"],
    }).trim();
  } catch {
    return cwd;
  }
}

function eventName(input) {
  return String(input && input.hook_event_name ? input.hook_event_name : "");
}

function truncateText(value, maxChars) {
  const text = String(value || "");
  if (text.length <= maxChars) return { text, truncated: false, originalLength: text.length };
  return {
    text: text.slice(0, maxChars) + "\n\n[Holdpoint output truncated to " + maxChars + " chars.]",
    truncated: true,
    originalLength: text.length,
  };
}

function isPathInsideRoot(repoRoot, absPath) {
  const rel = relative(repoRoot, absPath);
  return rel === "" || (!rel.startsWith("..") && !isAbsolute(rel));
}

function sendLiveEvent(input) {
  try {
    execSync(LIVE_COMMAND, {
      input: JSON.stringify(input),
      encoding: "utf8",
      stdio: ["pipe", "ignore", "ignore"],
    });
  } catch {
    // Live telemetry is best-effort and must never break Cursor's hook flow.
  }
}

function readSessionContext(repoRoot) {
  const configPath = join(repoRoot, ".github/holdpoint/generated/checks.immutable.json");
  if (!existsSync(configPath)) return undefined;
  try {
    const config = JSON.parse(readFileSync(configPath, "utf8"));
    const files = Array.isArray(config.session_context_files) ? config.session_context_files : [];
    const parts = [];
    for (const file of files) {
      if (typeof file !== "string" || !file.trim()) continue;
      const abs = resolve(repoRoot, file);
      if (!isPathInsideRoot(repoRoot, abs) || !existsSync(abs)) continue;
      try {
        parts.push("<!-- " + file + " -->\n" + readFileSync(abs, "utf8"));
      } catch {}
    }
    if (parts.length === 0) return undefined;
    const context = truncateText(parts.join("\n\n"), MAX_CONTEXT_CHARS);
    return {
      additional_context: context.text,
      truncated: context.truncated,
      originalLength: context.originalLength,
      emittedLength: context.text.length,
    };
  } catch {
    return undefined;
  }
}

function runHoldpointChecks(repoRoot) {
  const startedAt = Date.now();
  try {
    const output = execSync(CHECK_COMMAND, {
      cwd: repoRoot,
      stdio: "pipe",
      encoding: "utf8",
      maxBuffer: CHECK_MAX_BUFFER_BYTES,
    });
    return {
      ok: true,
      durationMs: Date.now() - startedAt,
      output: String(output || "").trim(),
    };
  } catch (error) {
    const output = [error && error.stdout, error && error.stderr, error && error.message]
      .filter(Boolean)
      .join("\n")
      .trim();
    const truncated = truncateText(output, MAX_CHECK_OUTPUT_CHARS);
    return {
      ok: false,
      durationMs: Date.now() - startedAt,
      output: truncated.text || "Holdpoint checks failed. Fix the issues above, then re-attempt.",
      truncated: truncated.truncated,
      originalLength: truncated.originalLength,
    };
  }
}

function shouldRunCompletionChecks(input) {
  const name = eventName(input);
  if (name === "stop") return true;
  if (name === "subagentStop") {
    return input && input.status === "completed";
  }
  return false;
}

const input = readInput();
const cwd = typeof input.cwd === "string" ? input.cwd : process.cwd();
const repoRoot = resolveRepoRoot(cwd);
const name = eventName(input);

if (name === "sessionStart") {
  const context = readSessionContext(repoRoot);
  sendLiveEvent({
    ...input,
    holdpoint_context: context
      ? {
          truncated: context.truncated,
          originalLength: context.originalLength,
          emittedLength: context.emittedLength,
        }
      : undefined,
  });
  if (context?.additional_context) {
    writeFileSync(1, JSON.stringify({ additional_context: context.additional_context }) + "\n");
  }
  process.exit(0);
}

if (shouldRunCompletionChecks(input)) {
  const result = runHoldpointChecks(repoRoot);
  sendLiveEvent({ ...input, holdpoint_check: result });
  if (result.ok) {
    process.exit(0);
  }
  process.stdout.write(
    JSON.stringify({
      followup_message:
        result.output +
        "\n\nHoldpoint checks failed. Fix the issues above, then run the checks again before finishing.",
    }) + "\n",
  );
  process.exit(0);
}

sendLiveEvent(input);

if (
  name === "preToolUse" ||
  name === "beforeShellExecution" ||
  name === "beforeMCPExecution" ||
  name === "beforeReadFile" ||
  name === "subagentStart"
) {
  process.stdout.write(JSON.stringify({ permission: "allow" }) + "\n");
} else if (name === "beforeSubmitPrompt") {
  process.stdout.write(JSON.stringify({ continue: true }) + "\n");
}
process.exit(0);
