import { existsSync, readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname } from "node:path";

const START_MARKER =
  "<!-- HOLDPOINT_MANAGED — content between these markers is auto-generated by holdpoint init / holdpoint update -->";
const END_MARKER = "<!-- /HOLDPOINT_MANAGED -->";

/** Canonical breadcrumb content. Same wording for every agent on purpose. */
export const BREADCRUMB_BODY = `## Holdpoint workflow

This repo uses [Holdpoint](https://holdpoint.dev) to gate task completion on deterministic checks.

Before marking any task done:

1. Run \`holdpoint check\` (or it will run automatically via Stop / TaskCompleted hooks).
2. Fix any failures. Re-run until exit 0.
3. Never bypass with \`--no-verify\` or by skipping the agent's stop hook.

Full workflow reference: [\`MASTER_PROMPT.md\`](./MASTER_PROMPT.md) (always injected at session start).
Deep reference: [\`HOLDPOINT_REFERENCE.md\`](./HOLDPOINT_REFERENCE.md) (read on demand).
Active checks: [\`checks.yaml\`](./checks.yaml).`;

/**
 * Idempotently splice the Holdpoint breadcrumb into a markdown instructions file.
 * - If the file is missing and createIfMissing: write a new file containing only the breadcrumb block.
 * - If the file has the markers: replace content between them.
 * - If the file exists but has no markers: append the breadcrumb block separated by a blank line.
 * Content outside the markers is never touched.
 */
export function spliceBreadcrumb(
  filePath: string,
  body: string = BREADCRUMB_BODY,
  createIfMissing = true,
): void {
  const block = `${START_MARKER}\n\n${body}\n\n${END_MARKER}`;
  if (!existsSync(filePath)) {
    if (!createIfMissing) return;
    mkdirSync(dirname(filePath), { recursive: true });
    writeFileSync(filePath, block + "\n", "utf8");
    return;
  }
  const existing = readFileSync(filePath, "utf8");
  const startIdx = existing.indexOf(START_MARKER);
  const endIdx = existing.indexOf(END_MARKER);
  if (startIdx !== -1 && endIdx !== -1 && endIdx > startIdx) {
    const before = existing.slice(0, startIdx);
    const after = existing.slice(endIdx + END_MARKER.length);
    writeFileSync(filePath, before + block + after, "utf8");
    return;
  }
  const sep = existing.endsWith("\n") ? "\n" : "\n\n";
  writeFileSync(filePath, existing + sep + block + "\n", "utf8");
}
