import type { HoldpointConfig } from "@holdpoint/types";

// Markers used to splice the Holdpoint block in/out of AGENTS.md
const AGENTS_MD_START = "<!-- holdpoint:start -->";
const AGENTS_MD_END = "<!-- holdpoint:end -->";

interface CodexHook {
  type: "command";
  command: string;
  timeout: number;
  statusMessage: string;
}

interface CodexHookGroup {
  hooks: CodexHook[];
}

interface CodexHooksJson {
  hooks: {
    Stop: CodexHookGroup[];
  };
}

/**
 * Generate `.codex/hooks.json` content.
 *
 * Registers a `Stop` hook that runs `.codex/holdpoint-check.mjs` before Codex
 * ends each turn. The script exits 2 on check failure so Codex continues working
 * rather than stopping with a hook error (exit 1 = hook failure → Codex stops).
 *
 * Design note: this file is fully managed by Holdpoint. Users who need additional
 * Codex hooks should add them in `.codex/config.toml` — Codex loads both files and
 * merges them, so there is no conflict.
 */
export function buildHooksJson(_config: HoldpointConfig): string {
  const json: CodexHooksJson = {
    hooks: {
      Stop: [
        {
          hooks: [
            {
              type: "command",
              // Shell expansion finds the git root so the hook works regardless of
              // which subdirectory Codex was launched from.
              command:
                'node "$(git rev-parse --show-toplevel 2>/dev/null || pwd)/.codex/holdpoint-check.mjs"',
              // Use Codex's default 600s timeout; shorter values risk treating slow
              // checks as hook failures (which stops Codex instead of continuing).
              timeout: 600,
              statusMessage: "Running Holdpoint checks…",
            },
          ],
        },
      ],
    },
  };
  return JSON.stringify(json, null, 2) + "\n";
}

/**
 * Generate `.codex/holdpoint-check.mjs` — the Node.js script invoked by the
 * Stop hook. It runs `holdpoint check --staged` from the git root, then:
 * - exits 0 if all checks pass → Codex stops normally
 * - exits 2 if any check fails → Codex keeps going and injects the failure
 *   output as a new user prompt so the agent can fix the issues
 *
 * Using a script file (rather than inline bash) keeps the hook command short,
 * handles the exit-code conversion portably, and runs from the git root so
 * checks.yaml is always found regardless of session cwd.
 */
export function buildCheckScript(): string {
  return `#!/usr/bin/env node
// AUTO-GENERATED by Holdpoint — do not edit. Re-generate: npx holdpoint update
import { execSync } from "node:child_process";

const root = (() => {
  try {
    return execSync("git rev-parse --show-toplevel", { encoding: "utf8" }).trim();
  } catch {
    return process.cwd();
  }
})();

try {
  execSync("npx holdpoint@latest check --staged", {
    cwd: root,
    stdio: "inherit",
    encoding: "utf8",
  });
  process.exit(0);
} catch (err) {
  // Capture any output that wasn't already written to stdout/stderr via inherit
  const extra = [err.stdout, err.stderr].filter(Boolean).join("\\n").trim();
  process.stderr.write(
    (extra ? extra + "\\n\\n" : "") +
      "Holdpoint checks failed. Fix the issues above, then re-attempt.\\n"
  );
  process.exit(2);
}
`;
}

/**
 * Generate the Holdpoint block for `AGENTS.md`.
 *
 * Returns just the block content including its start/end markers so the caller
 * can splice it into an existing AGENTS.md or create a new one.
 *
 * Codex natively reads AGENTS.md and follows its instructions, making this a
 * belt-and-suspenders layer on top of the Stop hook enforcement.
 */
export function buildAgentsMd(config: HoldpointConfig): string {
  const deterministicList = config.checks
    .filter((c) => c.cmd !== undefined)
    .map(
      (c) =>
        `  - [${Array.isArray(c.when) ? c.when.join(", ") : (c.when ?? "always")}] **${c.label}**: \`${c.cmd}\``,
    )
    .join("\n");

  const promptList = config.checks
    .filter((c) => c.prompt !== undefined)
    .map(
      (c) =>
        `  - [${Array.isArray(c.when) ? c.when.join(", ") : (c.when ?? "always")}] **${c.label}**: ${c.prompt}`,
    )
    .join("\n");

  return `${AGENTS_MD_START}
## Holdpoint Checks (auto-generated — do not edit this block)

Before marking ANY task complete, you MUST run all checks and confirm they pass:

\`\`\`sh
npx holdpoint@latest check --staged
\`\`\`

### Deterministic checks (automated)
${deterministicList || "  *(none configured)*"}

### Prompt checks (manual verification required)
${promptList || "  *(none configured)*"}

If \`holdpoint check\` exits non-zero, fix all failures before finishing.
For prompt checks, explicitly confirm in your response that you have acted on each item.
${AGENTS_MD_END}`;
}

/**
 * Splice the Holdpoint block into `existingContent` (full AGENTS.md text).
 * If the block is already present (identified by markers), replaces it.
 * Otherwise appends it.
 */
export function spliceAgentsMd(existingContent: string, config: HoldpointConfig): string {
  const block = buildAgentsMd(config);
  const start = existingContent.indexOf(AGENTS_MD_START);
  const end = existingContent.indexOf(AGENTS_MD_END);
  if (start !== -1 && end !== -1) {
    return (
      existingContent.slice(0, start) + block + existingContent.slice(end + AGENTS_MD_END.length)
    );
  }
  return existingContent.trimEnd() + "\n\n" + block + "\n";
}
