import type { HoldpointConfig } from "@holdpoint/types";

interface CodexHook {
  type: "command";
  command: string;
  timeout: number;
  statusMessage: string;
}

interface CodexHookGroup {
  matcher?: string;
  hooks: CodexHook[];
}

interface CodexHooksJson {
  hooks: Partial<
    Record<
      | "SessionStart"
      | "UserPromptSubmit"
      | "PreToolUse"
      | "PermissionRequest"
      | "PostToolUse"
      | "PreCompact"
      | "PostCompact"
      | "SubagentStart"
      | "SubagentStop"
      | "Stop",
      CodexHookGroup[]
    >
  >;
}

const HOOK_COMMAND =
  'node "$(git rev-parse --show-toplevel 2>/dev/null || pwd)/.codex/holdpoint-check.mjs"';

function hook(timeout: number, statusMessage: string, matcher?: string): CodexHookGroup[] {
  return [
    {
      ...(matcher ? { matcher } : {}),
      hooks: [
        {
          type: "command",
          // Use git root resolution so the hook finds the script regardless of
          // which subdirectory Codex was launched from.
          command: HOOK_COMMAND,
          timeout,
          statusMessage,
        },
      ],
    },
  ];
}

/**
 * Generate `.codex/hooks.json` content.
 *
 * Registers every command-hook event Codex exposes today. The same dispatcher
 * script handles all events: most are fast Live telemetry only, SessionStart /
 * SubagentStart can inject configured context, and Stop / SubagentStop run the
 * completion gate.
 *
 * Users who need additional Codex hooks should create a separate JSON file in
 * .codex/ (e.g. .codex/my-hooks.json) or use a separate config.toml section.
 * Do NOT mix hooks.json and inline [hooks] in config.toml in the same layer —
 * Codex warns at startup when both exist.
 */
export function buildHooksJson(config: HoldpointConfig): string {
  const hooks: CodexHooksJson["hooks"] = {
    UserPromptSubmit: hook(30, "Recording Holdpoint prompt telemetry…"),
    PreToolUse: hook(30, "Recording Holdpoint tool telemetry…"),
    PermissionRequest: hook(30, "Recording Holdpoint permission telemetry…"),
    PostToolUse: hook(30, "Recording Holdpoint tool result telemetry…"),
    PreCompact: hook(30, "Recording Holdpoint compaction telemetry…"),
    PostCompact: hook(30, "Recording Holdpoint compaction telemetry…"),
    SubagentStart: hook(30, "Loading Holdpoint subagent context…"),
    SubagentStop: hook(600, "Running Holdpoint subagent checks…"),
    // Codex default is 600 s; shorter risks premature hook failure on slow checks.
    Stop: hook(600, "Running Holdpoint checks…"),
  };

  // Add SessionStart only when context files are configured — avoids spawning a
  // subprocess on every session start when there is nothing to inject.
  if (config?.session_context_files?.length) {
    hooks.SessionStart = hook(30, "Loading Holdpoint context…");
  }

  return JSON.stringify({ hooks }, null, 2) + "\n";
}

/**
 * Generate `.codex/config.toml` content (or the fragment to append to an existing one).
 *
 * Explicitly enables hooks at the repo level. Hooks are on by default in Codex, but
 * writing this makes the intent clear and prevents accidental user-level `hooks = false`
 * from silently disabling holdpoint enforcement.
 *
 * Usage: write the full return value if the file doesn't exist. If it does exist and
 * already contains a [features] section, leave it — trust the user's settings.
 * If it exists without [features], append the returned fragment.
 */
export function buildConfigToml(): string {
  return `# Generated by Holdpoint. Ensure hooks are active for this project.
[features]
hooks = true
`;
}

/**
 * Generate `.codex/holdpoint-check.mjs` — invoked by both the SessionStart and
 * Stop hooks. Dispatches on `hook_event_name` from Codex's JSON stdin.
 *
 * SessionStart → reads checks.immutable.json, injects session_context_files as
 *   JSON additionalContext. Uses JSON (not YAML) because the script is plain .mjs
 *   with no bundler — JSON.parse is native, a YAML parser is not.
 *
 * Stop → runs the holdpoint CLI check command. Key correctness points per the
 *   Codex hook spec:
 *   - stdio: "pipe" (not "inherit") so CLI output never lands on hook stdout as
 *     plain text — Codex Stop requires JSON on stdout or no output; plain text
 *     on exit 0 is invalid and causes parse errors.
 *   - exit 0, no stdout on success → Codex stops normally.
 *   - exit 2, failure text on stderr → Codex creates a continuation prompt from
 *     the stderr text so the agent iterates to fix the issues.
 */
export function buildCheckScript(config?: HoldpointConfig): string {
  const stopCommand =
    config?.engines?.codex?.stop_command ?? "node_modules/.bin/holdpoint check --staged";
  return `#!/usr/bin/env node
// AUTO-GENERATED by Holdpoint — do not edit. Re-generate: npx holdpoint update
import { execSync, spawn } from "node:child_process";
import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { isAbsolute, join, relative, resolve } from "node:path";

const STOP_COMMAND = ${JSON.stringify(stopCommand)};
const LIVE_COMMAND = "node_modules/.bin/holdpoint";
const LIVE_ARGS = ["event", "--engine", "codex", "--from-hook"];
const MAX_CONTEXT_CHARS = 100_000;
const MAX_CHECK_OUTPUT_CHARS = 60_000;
const CHECK_MAX_BUFFER_BYTES = 1024 * 1024 * 10;

const root = (() => {
  try {
    return execSync("git rev-parse --show-toplevel", {
      encoding: "utf8",
      stdio: ["ignore", "pipe", "ignore"],
    }).trim();
  } catch {
    return process.cwd();
  }
})();

// Codex sends a JSON object on stdin for every hook event.
let input = {};
try {
  const raw = readFileSync(0 /* stdin fd */, "utf8").trim();
  if (raw) input = JSON.parse(raw);
} catch { /* non-JSON or empty stdin — default to Stop behaviour */ }

function hookEventName() {
  return typeof input.hook_event_name === "string" ? input.hook_event_name : "Stop";
}

function truncateText(value, maxChars) {
  const text = String(value || "");
  if (text.length <= maxChars) return { text, truncated: false, originalLength: text.length };
  return {
    text: text.slice(0, maxChars) + "\\n\\n[Holdpoint output truncated to " + maxChars + " chars.]",
    truncated: true,
    originalLength: text.length,
  };
}

function isPathInsideRoot(repoRoot, absPath) {
  const rel = relative(repoRoot, absPath);
  return rel === "" || (!rel.startsWith("..") && !isAbsolute(rel));
}

function sendLiveEvent(payload) {
  try {
    const child = spawn(LIVE_COMMAND, LIVE_ARGS, {
      cwd: root,
      stdio: ["pipe", "ignore", "ignore"],
      detached: true,
    });
    child.stdin.end(JSON.stringify(payload));
    child.unref();
  } catch {
    // Live telemetry is best-effort and must never break Codex's hook flow.
  }
}

function readSessionContext() {
  const configPath = join(root, ".github/holdpoint/generated/checks.immutable.json");
  if (!existsSync(configPath)) return undefined;
  try {
    const cfg = JSON.parse(readFileSync(configPath, "utf8"));
    const files = Array.isArray(cfg.session_context_files) ? cfg.session_context_files : [];
    const parts = [];
    for (const file of files) {
      if (typeof file !== "string" || !file.trim()) continue;
      const abs = resolve(root, file);
      if (!isPathInsideRoot(root, abs) || !existsSync(abs)) continue;
      try { parts.push(\`<!-- \${file} -->\\n\${readFileSync(abs, "utf8")}\`); } catch {}
    }
    if (parts.length === 0) return undefined;
    const context = truncateText(parts.join("\\n\\n"), MAX_CONTEXT_CHARS);
    return {
      additionalContext: context.text,
      truncated: context.truncated,
      originalLength: context.originalLength,
      emittedLength: context.text.length,
    };
  } catch {
    return undefined;
  }
}

function outputAdditionalContext(eventName, context) {
  if (!context?.additionalContext) return;
  writeFileSync(1, JSON.stringify({
    hookSpecificOutput: {
      hookEventName: eventName,
      additionalContext: context.additionalContext,
    },
  }));
}

function runHoldpointChecks() {
  const startedAt = Date.now();
  try {
    // stdio: "pipe" — CLI output must NOT reach hook stdout as plain text.
    const output = execSync(STOP_COMMAND, {
      cwd: root,
      stdio: "pipe",
      encoding: "utf8",
      maxBuffer: CHECK_MAX_BUFFER_BYTES,
    });
    return {
      ok: true,
      durationMs: Date.now() - startedAt,
      output: String(output || "").trim(),
    };
  } catch (err) {
    const output = [err.stdout, err.stderr, err.message].filter(Boolean).join("\\n").trim();
    const truncated = truncateText(output, MAX_CHECK_OUTPUT_CHARS);
    return {
      ok: false,
      durationMs: Date.now() - startedAt,
      output: truncated.text || "Holdpoint checks failed. Fix the issues above, then re-attempt.",
      truncated: truncated.truncated,
      originalLength: truncated.originalLength,
    };
  }
}

// ── SessionStart: inject session_context_files as additionalContext ────────────
const eventName = hookEventName();

if (eventName === "SessionStart" || eventName === "SubagentStart") {
  const context = readSessionContext();
  sendLiveEvent({
    ...input,
    holdpoint_context: context
      ? { truncated: context.truncated, originalLength: context.originalLength, emittedLength: context.emittedLength }
      : undefined,
  });
  outputAdditionalContext(eventName, context);
  process.exit(0);
}

// ── Stop: run checks, exit 0 (pass) or exit 2 (continue with feedback) ─────────
if (eventName === "Stop" || eventName === "SubagentStop") {
  if (input.stop_hook_active === true) {
    sendLiveEvent({ ...input, holdpoint_check: { skipped: true, reason: "stop_hook_active" } });
    process.exit(0);
  }
  const result = runHoldpointChecks();
  sendLiveEvent({ ...input, holdpoint_check: result });
  if (result.ok) {
    process.exit(0);
  }
  // Write captured check output to stderr — Codex uses this as the continuation prompt.
  process.stderr.write(
    result.output + "\\n\\nHoldpoint checks failed. Fix the issues above, then re-attempt.\\n",
  );
  process.exit(2);
}

// Other hook events are telemetry-only. Do not emit pass-through allow decisions:
// PermissionRequest allow would auto-approve escalations, and PreToolUse allow
// has rewrite semantics in Codex. Empty stdout means "no decision".
sendLiveEvent(input);
process.exit(0);
`;
}

/**
 * Generate a standalone context-injection script for SessionStart tests.
 * Runtime hooks use the same dispatcher script so Stop/SubagentStop behavior
 * stays wired through one generated file.
 */
export function buildContextScript(): string {
  return buildCheckScript();
}
