#!/usr/bin/env node
// AUTO-GENERATED by @holdpoint/engine-copilot — do not edit manually.
// Loaded by the Copilot CLI at startup from .github/extensions/holdpoint/extension.mjs
// beforeTaskComplete fires before the agent calls task_complete.

import { execSync } from "node:child_process";
import { existsSync, readFileSync } from "node:fs";
import { join, resolve, sep } from "node:path";

function resolveRepoRoot() {
  try {
    return execSync("git rev-parse --show-toplevel", {
      encoding: "utf8",
      stdio: ["pipe", "pipe", "ignore"],
    }).trim();
  } catch {
    return process.cwd();
  }
}

function getStagedFiles(repoRoot) {
  try {
    return execSync("git diff --cached --name-only", {
      encoding: "utf8",
      stdio: ["pipe", "pipe", "ignore"],
      cwd: repoRoot,
    })
      .trim()
      .split("\n")
      .filter(Boolean);
  } catch {
    return [];
  }
}

function matchesWhen(when, changedFiles, userPatterns) {
  if (!when) return true;
  if (changedFiles.includes("__all__") || changedFiles.length === 0) return true;
  const patterns = {
    frontend: [/\.(tsx|jsx|css|scss)$/, /tailwind\.config\./, /postcss\.config\./, /^apps\/(builder|web)\//],
    backend: [/(^|\/)api\//, /(^|\/)server\//, /(^|\/)routes\//, /(^|\/)controllers\//, /(^|\/)middleware\//, /^packages\/[^/]+\/src\//],
    prisma: [/\.prisma$/, /(^|\/)prisma\//],
    socket: [/(^|\/)socket\//, /(^|\/)ws\//, /(^|\/)websocket\//],
    visual: [/\.stories\.(tsx?|jsx?)$/, /(^|\/)__screenshots__\//, /\.snap$/],
    python: [/\.pyi?$/, /requirements[^/]*\.txt$/, /pyproject\.toml$/, /setup\.(py|cfg)$/, /(^|\/)Pipfile(\.lock)?$/, /uv\.lock$/, /pytest\.ini$/, /tox\.ini$/],
    go: [/\.go$/, /go\.(mod|sum)$/],
    rust: [/\.rs$/, /Cargo\.(toml|lock)$/],
    java: [/\.(java|kt)$/, /\.gradle(\.kts)?$/, /pom\.xml$/],
    ruby: [/\.rb$/, /(^|\/)Gemfile(\.lock)?$/, /(^|\/)Rakefile$/],
    database: [/\.sql$/, /(^|\/)(migrations?|migration)\//, /(^|\/)prisma\//, /\.prisma$/, /(^|\/)db\//, /(^|\/)database\//, /(^|\/)(seeds?|seed)\//, /alembic\.ini$/],
    testing: [/\.(test|spec)\.(tsx?|jsx?|py|rb|go)$/, /(^|\/)__tests__\//, /(^|\/)tests?\//, /(^|\/)spec\//],
    infra: [/(^|\/)Dockerfile(\..*)?$/, /(^|\/)docker-compose/, /\.(tf|tfvars|hcl)$/, /(^|\/)k8s\//, /(^|\/)kubernetes\//, /(^|\/)(helm|charts)\//, /\.dockerignore$/],
    ci: [/(^|\/)(\.github\/workflows|\.circleci)\//, /(^|\/)Jenkinsfile$/, /(^|\/)\.(gitlab-ci|travis|drone)\.yml$/],
    docs: [/\.(mdx|rst)$/, /(^|\/)(docs|documentation)\//],
    structural: [
      /(^|\/|\\)package\.json$/, /tsconfig[^/]*\.json$/, /requirements[^/]*\.txt$/, /pyproject\.toml$/,
      /(^|\/)Pipfile(\.lock)?$/, /setup\.(py|cfg)$/, /pytest\.ini$/, /tox\.ini$/, /go\.mod$/, /Cargo\.toml$/,
      /pom\.xml$/, /build\.gradle(\.kts)?$/, /(^|\/)Gemfile(\.lock)?$/, /vitest\.config\./, /jest\.config\./,
      /playwright\.config\./, /eslint\.config\./, /\.eslintrc/, /biome\.json$/, /prettier\.config\./, /\.prettierrc/,
      /next\.config\./, /(^|\/)Dockerfile/, /(^|\/)docker-compose[^/]*\.(yml|yaml)$/, /\.tf$/, /prisma\/schema\.prisma$/,
      /openapi\.(yaml|yml|json)$/, /\.github\/workflows\/[^/]+\.(yml|yaml)$/,
      /(^|\/)(\.circleci\/|Jenkinsfile$|\.gitlab-ci\.yml$|\.travis\.yml$)/,
    ],
  };
  if (when in patterns) {
    return changedFiles.some((f) => (patterns[when] ?? []).some((re) => re.test(f)));
  }
  if (userPatterns && when in userPatterns) {
    return changedFiles.some((f) => new RegExp(userPatterns[when]).test(f));
  }
  return changedFiles.some((f) => new RegExp(when).test(f));
}

function runCheck(check, repoRoot) {
  if (!check.cmd) return { status: "pending" };
  try {
    const output = execSync(check.cmd, { encoding: "utf8", timeout: 60000, stdio: "pipe", cwd: repoRoot });
    return { status: "pass", output };
  } catch (e) {
    return { status: "fail", output: [e.stdout, e.stderr].filter(Boolean).join("\n"), exitCode: e.status ?? 1 };
  }
}

export default {
  async beforeTaskComplete() {
    try {
      const repoRoot = resolveRepoRoot();
      const changedFiles = getStagedFiles(repoRoot);

      // Re-sync if checks.yaml is staged
      if (changedFiles.some((f) => /^checks\.yaml$/.test(f))) {
        const sync = runCheck({ cmd: "npx holdpoint update" }, repoRoot);
        if (sync.status === "fail") {
          return {
            decision: "block",
            reason: `Holdpoint: checks.yaml changed but \`holdpoint update\` failed:\n\n${(sync.output ?? "").trim()}\n\nFix the error above, then retry.`,
          };
        }
      }

      const configPath = join(repoRoot, ".github/holdpoint/generated/checks.immutable.json");
      if (!existsSync(configPath)) {
        return {
          decision: "block",
          reason: "Holdpoint: .github/holdpoint/generated/checks.immutable.json not found — run: npx holdpoint update",
        };
      }

      const config = JSON.parse(readFileSync(configPath, "utf8"));
      const failures = [];

      for (const check of config.checks.filter((c) => c.cmd !== undefined)) {
        if (!matchesWhen(check.when, changedFiles, config.patterns)) continue;
        const result = runCheck(check, repoRoot);
        if (result.status === "fail") failures.push({ check, result });
      }

      const promptChecks = config.checks.filter(
        (c) => c.prompt !== undefined && matchesWhen(c.when, changedFiles, config.patterns),
      );

      if (failures.length > 0) {
        const summary = failures.map((f) => `  ✗ [${f.check.label}]\n${(f.result.output ?? "").trim()}`).join("\n\n");
        const promptSection =
          promptChecks.length > 0
            ? `\n\nComplete these actions before committing:\n${promptChecks.map((c) => `  □ [${c.label}] ${c.prompt ?? ""}`).join("\n")}`
            : "";
        return {
          decision: "block",
          reason: `Holdpoint: ${failures.length} check(s) failed:\n\n${summary}${promptSection}\n\nFix the above issues before marking the task complete.`,
        };
      }

      if (promptChecks.length > 0) {
        const list = promptChecks.map((c) => `  □ [${c.label}] ${c.prompt ?? ""}`).join("\n");
        return {
          decision: "block",
          reason: `Holdpoint: carry out these agent prompts before marking the task complete:\n${list}`,
        };
      }

      return { decision: "allow" };
    } catch (err) {
      return {
        decision: "block",
        reason: `Holdpoint hook error: ${err instanceof Error ? err.message : String(err)}`,
      };
    }
  },
};
