// AUTO-GENERATED by @holdpoint/engine-copilot — do not edit manually.

import { joinSession } from '@github/copilot-sdk/extension';
import { execSync } from 'node:child_process';

function resolveRepoRoot(cwd) {
  try {
    return execSync('git rev-parse --show-toplevel', {
      encoding: 'utf8',
      stdio: ['pipe', 'pipe', 'ignore'],
      cwd: cwd ?? process.cwd(),
    }).trim();
  } catch {
    return cwd ?? process.cwd();
  }
}

const session = await joinSession({
  hooks: {
    onPreToolUse: async (input) => {
      if (input.toolName !== 'task_complete') return;
      const repoRoot = resolveRepoRoot(input.cwd);
      await session.log('Holdpoint: running checks\u2026', { ephemeral: true });
      try {
        execSync("node_modules/.bin/holdpoint check --staged", {
          cwd: repoRoot,
          stdio: 'pipe',
          encoding: 'utf8',
        });
      } catch (e) {
        const output = [e.stdout, e.stderr].filter(Boolean).join('\n').trim();
        return {
          permissionDecision: 'deny',
          permissionDecisionReason: output || 'Holdpoint checks failed. Fix the issues above, then re-attempt.',
        };
      }
    },
  },
});
