// AUTO-GENERATED by @holdpoint/engine-copilot — do not edit manually.

import { joinSession } from '@github/copilot-sdk/extension';
import { execFileSync, execSync } from 'node:child_process';
import { createHash, randomUUID } from 'node:crypto';
import { existsSync, readFileSync, realpathSync } from 'node:fs';
import { homedir } from 'node:os';
import { basename, isAbsolute, join, relative, resolve } from 'node:path';

// Generated from @holdpoint/types buildSecurityScanScript — do not edit by hand.
const SECURITY_SCAN_VERIFIED = new Set(["@anthropic-ai/mcp-server-brave-search","@anthropic-ai/mcp-server-fetch","@modelcontextprotocol/server-filesystem","@modelcontextprotocol/server-github","@modelcontextprotocol/server-gitlab","@modelcontextprotocol/server-google-maps","@modelcontextprotocol/server-postgres","@modelcontextprotocol/server-slack","@modelcontextprotocol/server-memory","@modelcontextprotocol/server-puppeteer","@modelcontextprotocol/server-sequential-thinking","@modelcontextprotocol/server-everything"]);
const SECURITY_SCAN_SEVERITIES = new Set(["high", "critical"]);
function securityScanReadJson(path) {
  try { return JSON.parse(readFileSync(path, "utf8")); } catch { return undefined; }
}
function securityScanStringArray(value) {
  return Array.isArray(value) ? value.filter((entry) => typeof entry === "string") : [];
}
function securityScanPackageName(value) {
  const normalized = String(value || "").replace(/\\/g, "/");
  const idx = normalized.lastIndexOf("node_modules/");
  if (idx >= 0) {
    const parts = normalized.slice(idx + "node_modules/".length).split("/").filter(Boolean);
    if (parts[0] && parts[0].startsWith("@") && parts[1]) return parts[0] + "/" + parts[1];
    return parts[0];
  }
  if (normalized.startsWith("@")) {
    const parts = normalized.split("/");
    return parts[0] && parts[1] ? parts[0] + "/" + parts[1] : undefined;
  }
  if (!normalized.includes("/") && /^[a-z0-9@._-]+$/i.test(normalized)) return normalized;
  return undefined;
}
function securityScanMcpEntries(config) {
  if (!config || typeof config !== "object") return [];
  const servers = config.mcpServers || config.servers;
  if (!servers || typeof servers !== "object" || Array.isArray(servers)) return [];
  return Object.entries(servers).map(([key, raw]) => {
    const server = raw && typeof raw === "object" && !Array.isArray(raw) ? raw : {};
    return {
      key,
      name: typeof server.name === "string" ? server.name : undefined,
      command: typeof server.command === "string" ? server.command : undefined,
      args: securityScanStringArray(server.args),
    };
  });
}
// Strip a leading version/dist-tag from a package spec, leaving the bare name.
// "@scope/name@1.2.3" -> "@scope/name"; "pkg@latest" -> "pkg". Leaves paths/urls alone.
function securityScanStripVersion(spec) {
  const s = String(spec || "");
  if (!s) return s;
  if (s.startsWith("@")) {
    // Scoped: keep through the "@scope/name" segment, then cut at a later "@".
    const slash = s.indexOf("/");
    if (slash < 0) return s;
    const rest = s.slice(slash + 1);
    const at = rest.indexOf("@");
    return at >= 0 ? s.slice(0, slash + 1 + at) : s;
  }
  const at = s.indexOf("@");
  return at > 0 ? s.slice(0, at) : s;
}
// Pick the first non-flag argument from args, skipping anything starting with "-".
function securityScanFirstNonFlag(args, startIndex) {
  for (let i = startIndex || 0; i < args.length; i++) {
    const a = args[i];
    if (typeof a === "string" && a && !a.startsWith("-")) return a;
  }
  return undefined;
}
// Derive the single package that will actually execute, from command + args ONLY.
// Returns { pkg, checkable } where checkable indicates the pkg is an npm name we
// can look up in the verified registry. NEVER consults entry.name or unrelated args.
function securityScanExecutedPackage(entry) {
  const command = entry.command;
  const args = entry.args || [];
  if (!command) return { pkg: undefined, checkable: false };
  const base = securityScanPackageName(command);
  if (command === "npx" || command === "bunx") {
    const target = securityScanFirstNonFlag(args, 0);
    if (!target) return { pkg: undefined, checkable: false };
    return { pkg: securityScanStripVersion(target), checkable: true };
  }
  if ((command === "pnpm" || command === "yarn") && args[0] === "dlx") {
    const target = securityScanFirstNonFlag(args, 1);
    if (!target) return { pkg: undefined, checkable: false };
    return { pkg: securityScanStripVersion(target), checkable: true };
  }
  if (command === "uvx") {
    // Python/uv package — not resolvable to an npm name.
    const target = securityScanFirstNonFlag(args, 0);
    return { pkg: target ? securityScanStripVersion(target) : undefined, checkable: false };
  }
  if (command === "node" || base === "node") {
    const script = securityScanFirstNonFlag(args, 0);
    const pkg = script ? securityScanPackageName(script) : undefined;
    return pkg ? { pkg, checkable: true } : { pkg: undefined, checkable: false };
  }
  // Command is itself a path / binary.
  return base ? { pkg: base, checkable: true } : { pkg: undefined, checkable: false };
}
function securityScanMcp(root) {
  const results = [];
  for (const file of [join(root, ".mcp.json"), join(root, ".claude/mcp.json")]) {
    if (!existsSync(file)) continue;
    for (const entry of securityScanMcpEntries(securityScanReadJson(file))) {
      const executed = securityScanExecutedPackage(entry);
      const verified = executed.checkable && executed.pkg ? SECURITY_SCAN_VERIFIED.has(executed.pkg) : false;
      results.push({ server: entry.name || entry.key, verified, checkable: executed.checkable });
    }
  }
  return results;
}
// Returns { pm, cmd } where pm is the display label and cmd is the full audit
// command string, or null when no lockfile is present.
function securityScanPackageManager(root) {
  if (existsSync(join(root, "pnpm-lock.yaml"))) return { pm: "pnpm", cmd: "pnpm audit --json" };
  if (existsSync(join(root, "yarn.lock"))) {
    // Yarn Berry (v2+) has no "yarn audit --json"; it uses "yarn npm audit".
    let berry = existsSync(join(root, ".yarnrc.yml"));
    if (!berry) {
      const pkg = securityScanReadJson(join(root, "package.json"));
      const pm = pkg && typeof pkg.packageManager === "string" ? pkg.packageManager : "";
      const m = /^yarn@(\d+)/.exec(pm);
      if (m && Number(m[1]) >= 2) berry = true;
    }
    return berry
      ? { pm: "yarn", cmd: "yarn npm audit --all --json" }
      : { pm: "yarn", cmd: "yarn audit --json" };
  }
  if (existsSync(join(root, "package-lock.json")) || existsSync(join(root, "npm-shrinkwrap.json"))) {
    return { pm: "npm", cmd: "npm audit --json" };
  }
  return null;
}
function securityScanFirstTitle(value) {
  if (typeof value === "string") return value;
  if (Array.isArray(value)) {
    for (const entry of value) {
      const title = securityScanFirstTitle(entry);
      if (title) return title;
    }
  }
  if (value && typeof value === "object" && typeof value.title === "string") return value.title;
  return undefined;
}
// #7: For npm v7+ transitive vulns, "via" is an array of STRINGS naming parent
// packages — those must never become the advisory title. Resolve a "via" value to
// a safe title: object entries with a string .title are real advisories; an array
// of plain strings falls back to "Vulnerable dependency (via <parent>)" so a raw
// package name never lands in the title slot.
function securityScanTitleFromVia(via) {
  const objectTitle = securityScanFirstTitle(
    Array.isArray(via)
      ? via.filter((entry) => entry && typeof entry === "object")
      : via && typeof via === "object" ? via : undefined,
  );
  if (objectTitle) return objectTitle;
  const parents = securityScanStringArray(Array.isArray(via) ? via : [via]);
  if (parents.length > 0) return "Vulnerable dependency (via " + parents[0] + ")";
  return undefined;
}
function securityScanAddFinding(findings, seen, name, severity, title) {
  if (!name || typeof severity !== "string") return;
  const normalizedSeverity = severity.toLowerCase();
  if (!SECURITY_SCAN_SEVERITIES.has(normalizedSeverity)) return;
  const normalizedTitle = securityScanFirstTitle(title) || "Security advisory";
  const key = name + "\0" + normalizedSeverity + "\0" + normalizedTitle;
  if (seen.has(key)) return;
  seen.add(key);
  findings.push({ name, severity: normalizedSeverity, title: normalizedTitle });
}
function securityScanParseAudit(raw) {
  const findings = [];
  const seen = new Set();
  const parseOne = (data) => {
    if (!data || typeof data !== "object") return;
    if (data.vulnerabilities && typeof data.vulnerabilities === "object") {
      for (const [name, vuln] of Object.entries(data.vulnerabilities)) {
        if (!vuln || typeof vuln !== "object") continue;
        // #7: resolve "via" safely so string-parent names never become the title.
        const title = vuln.via !== undefined ? securityScanTitleFromVia(vuln.via) : vuln.title;
        securityScanAddFinding(findings, seen, name, vuln.severity, title);
      }
    }
    if (data.advisories && typeof data.advisories === "object") {
      for (const advisory of Object.values(data.advisories)) {
        if (!advisory || typeof advisory !== "object") continue;
        securityScanAddFinding(findings, seen, advisory.module_name, advisory.severity, advisory.title);
      }
    }
    if (data.type === "auditAdvisory" && data.data && data.data.advisory) {
      const advisory = data.data.advisory;
      securityScanAddFinding(findings, seen, advisory.module_name, advisory.severity, advisory.title);
    }
  };
  try { parseOne(JSON.parse(raw)); }
  catch {
    for (const line of String(raw || "").split(/\r?\n/)) {
      if (!line.trim()) continue;
      try { parseOne(JSON.parse(line)); } catch {}
    }
  }
  // #4: sort by severity (critical outranks high) BEFORE capping so criticals are
  // never dropped by insertion order. Comparator is stable for equal severities.
  const rank = (s) => (s === "critical" ? 0 : 1);
  findings.sort((a, b) => rank(a.severity) - rank(b.severity));
  return findings.slice(0, 5);
}
function securityScanAudit(root) {
  const manager = securityScanPackageManager(root);
  if (!manager) return { pm: null, findings: [] };
  const pm = manager.pm;
  try {
    const stdout = execSync(manager.cmd, {
      cwd: root,
      encoding: "utf8",
      stdio: ["ignore", "pipe", "pipe"],
      maxBuffer: 1024 * 1024 * 10,
      timeout: 8000,
    });
    return { pm, findings: securityScanParseAudit(stdout) };
  } catch (err) {
    const stdout = err && typeof err.stdout === "string" ? err.stdout : "";
    if (stdout.trim()) {
      // #6: non-zero exit with JSON on stdout is the normal "vulns found" path.
      return { pm, findings: securityScanParseAudit(stdout) };
    }
    // #6: timeout / error with no usable stdout — return a sentinel so the banner
    // can distinguish "audit didn't complete" from "clean repo".
    return { pm, findings: [], error: "timeout" };
  }
}
function formatSecurityScan(root) {
  const mcp = securityScanMcp(root);
  // #1/#11: npm-checkable servers not in the registry are genuinely unreviewed;
  // non-checkable (uvx/python/unresolvable) servers get a calmer, separate group.
  const unverified = mcp.filter((entry) => !entry.verified && entry.checkable !== false);
  const nonCheckable = mcp.filter((entry) => entry.checkable === false);
  const audit = securityScanAudit(root);
  const auditDidNotComplete = audit.error && audit.findings.length === 0;
  if (
    unverified.length === 0 &&
    nonCheckable.length === 0 &&
    audit.findings.length === 0 &&
    !auditDidNotComplete
  ) {
    return null;
  }
  const lines = ["⚠ Holdpoint Security Scan", ""];
  if (unverified.length > 0) {
    lines.push("MCP servers — unverified:");
    for (const entry of unverified) lines.push("  • " + entry.server + " (source unknown — review before trusting)");
    lines.push("");
  }
  if (nonCheckable.length > 0) {
    lines.push("MCP servers — source not checkable (non-npm):");
    for (const entry of nonCheckable) lines.push("  • " + entry.server + " (can't verify automatically — review the source)");
    lines.push("");
  }
  if (audit.findings.length > 0) {
    lines.push((audit.pm || "npm") + " audit — high/critical:");
    for (const dep of audit.findings) lines.push("  • " + dep.name + " · " + dep.title + " (" + dep.severity + ")");
    lines.push("");
  } else if (auditDidNotComplete) {
    // #6: surface an incomplete audit so a timeout no longer looks like a clean repo.
    const pm = audit.pm || "npm";
    lines.push((audit.pm || "npm") + " audit — high/critical:");
    lines.push("  • dependency audit did not complete (timeout) — run `" + pm + " audit` manually");
    lines.push("");
  }
  lines.push("Review these before allowing the agent to install dependencies or invoke tools.");
  return lines.join("\n");
}

const LIVE_CAPS = {
  can_stream: true,
  can_control: true,
  can_modify_context: true,
  can_register_tools: true,
  control_online: false,
};
const MAX_QUEUED_EVENTS = 200;
const MAX_INJECT_NOTES = 5;
const INJECT_TTL_MS = 5 * 60 * 1000;
const PERMISSION_TIMEOUT_MS = 60 * 1000;
const MAX_CONTEXT_CHARS = 9000;
const MAX_CHECK_OUTPUT_CHARS = 8000;
const CHECK_MAX_BUFFER_BYTES = 10 * 1024 * 1024;

let session;
let sessionContext = null;
let bridgeSocket = null;
let reconnectTimer = null;
let warnedMissingWebSocket = false;
const bridgeQueue = [];
const toolCalls = new Map();
const pendingByKey = new Map();
const pendingByRequestId = new Map();
const injectQueue = [];

function resolveHoldpointHome() {
  return resolve(process.env.HOLDPOINT_HOME || join(homedir(), '.holdpoint'));
}

function readDaemonLock() {
  const lockPath = join(resolveHoldpointHome(), 'daemon.lock');
  if (!existsSync(lockPath)) return null;
  try {
    const parsed = JSON.parse(readFileSync(lockPath, 'utf8'));
    if (
      typeof parsed.port === 'number' &&
      typeof parsed.token === 'string' &&
      typeof parsed.host === 'string'
    ) {
      return parsed;
    }
  } catch {}
  return null;
}

function resolveRepoRoot(cwd) {
  try {
    return execSync('git rev-parse --show-toplevel', {
      encoding: 'utf8',
      stdio: ['pipe', 'pipe', 'ignore'],
      cwd: cwd ?? process.cwd(),
    }).trim();
  } catch {
    return cwd ?? process.cwd();
  }
}

function sha12(value) {
  return createHash('sha256').update(value).digest('hex').slice(0, 12);
}

function identifyProject(cwd) {
  try {
    const root = realpathSync(
      execFileSync('git', ['rev-parse', '--show-toplevel'], {
        cwd,
        encoding: 'utf8',
        stdio: ['ignore', 'pipe', 'ignore'],
      }).trim(),
    );
    return { hash: sha12(root), name: basename(root), root };
  } catch {
    const root = realpathSync(cwd);
    return { hash: sha12(root), name: basename(root), root };
  }
}

function buildSessionKey(projectHash, sessionId) {
  return projectHash + ':copilot:' + sessionId;
}

function ensureSessionContext(cwd) {
  if (sessionContext) return sessionContext;
  const repoRoot = resolveRepoRoot(cwd ?? process.cwd());
  const project = identifyProject(repoRoot);
  sessionContext = {
    repoRoot,
    project,
    sessionKey: buildSessionKey(project.hash, session.sessionId),
  };
  return sessionContext;
}

function truncateText(value, maxChars) {
  const text = String(value || '');
  if (text.length <= maxChars) return { text, truncated: false, originalLength: text.length };
  return {
    text: text.slice(0, maxChars) + '\n\n[Holdpoint output truncated to ' + maxChars + ' chars.]',
    truncated: true,
    originalLength: text.length,
  };
}

function isPathInsideRoot(repoRoot, absPath) {
  const rel = relative(repoRoot, absPath);
  return rel === '' || (!rel.startsWith('..') && !isAbsolute(rel));
}

function readConfig(repoRoot) {
  const configPath = join(repoRoot, '.github/holdpoint/generated/checks.immutable.json');
  if (!existsSync(configPath)) return {};
  try { return JSON.parse(readFileSync(configPath, 'utf8')); } catch { return {}; }
}

function readFileContext(repoRoot, file) {
  if (typeof file !== 'string' || !file.trim()) return null;
  const abs = resolve(repoRoot, file);
  if (!isPathInsideRoot(repoRoot, abs) || !existsSync(abs)) return null;
  try { return '<!-- ' + file + ' -->\n' + readFileSync(abs, 'utf8'); } catch { return null; }
}

// Gather agent context for a Holdpoint hook: configured session_context_files
// (session_start), per-check inject/prompt actions for that hook, and the
// top-level datetime (message_submit). Mirrors the other engines.
function gatherHookContext(repoRoot, hook) {
  const config = readConfig(repoRoot);
  const checks = Array.isArray(config.checks) ? config.checks : [];
  const parts = [];
  let hasDatetime = false;
  const addDatetime = () => {
    if (hasDatetime) return;
    hasDatetime = true;
    parts.push('Current date and time: ' + new Date().toISOString() + ' (UTC)\nProvided by Holdpoint — use this to avoid knowledge-cutoff confusion.');
  };

  if (hook === 'session_start') {
    const files = Array.isArray(config.session_context_files) ? config.session_context_files : [];
    for (const f of files) { const c = readFileContext(repoRoot, f); if (c) parts.push(c); }
    if (config.security_scan !== false) {
      const scan = formatSecurityScan(repoRoot);
      if (scan) parts.push(scan);
    }
  }
  for (const c of checks) {
    const on = typeof c.on === 'string' ? c.on : 'before_done';
    if (on !== hook) continue;
    if (c.inject && typeof c.inject === 'object') {
      if (c.inject.datetime === true) addDatetime();
      if (typeof c.inject.text === 'string' && c.inject.text.trim()) parts.push(c.inject.text);
      if (Array.isArray(c.inject.files)) for (const f of c.inject.files) { const x = readFileContext(repoRoot, f); if (x) parts.push(x); }
    } else if (typeof c.prompt === 'string' && c.prompt.trim()) {
      parts.push('Holdpoint reminder [' + (c.label || c.id || 'check') + ']: ' + c.prompt);
    }
  }
  if (hook === 'message_submit' && config.inject_datetime !== false) addDatetime();

  if (parts.length === 0) return undefined;
  const context = truncateText(parts.join('\n\n'), MAX_CONTEXT_CHARS);
  return {
    additionalContext: context.text,
    truncated: context.truncated,
    originalLength: context.originalLength,
    emittedLength: context.text.length,
  };
}

function hasCmdAt(repoRoot, hook) {
  const config = readConfig(repoRoot);
  const checks = Array.isArray(config.checks) ? config.checks : [];
  return checks.some((c) => typeof c.cmd === 'string' && (typeof c.on === 'string' ? c.on : 'before_done') === hook);
}

function runHoldpointChecks(repoRoot, command = "node_modules/.bin/holdpoint check --staged") {
  const startedAt = Date.now();
  try {
    const output = execSync(command, {
      cwd: repoRoot,
      stdio: 'pipe',
      encoding: 'utf8',
      maxBuffer: CHECK_MAX_BUFFER_BYTES,
    });
    return {
      ok: true,
      durationMs: Date.now() - startedAt,
      output: String(output || '').trim(),
    };
  } catch (error) {
    const output = [error && error.stdout, error && error.stderr, error && error.message]
      .filter(Boolean)
      .join('\n')
      .trim();
    const truncated = truncateText(output, MAX_CHECK_OUTPUT_CHARS);
    return {
      ok: false,
      durationMs: Date.now() - startedAt,
      output: truncated.text || 'Holdpoint checks failed. Fix the issues above, then re-attempt.',
      truncated: truncated.truncated,
      originalLength: truncated.originalLength,
    };
  }
}

function toTs(value) {
  if (typeof value === 'number' && Number.isFinite(value)) return value;
  const parsed = Date.parse(String(value ?? ''));
  return Number.isFinite(parsed) ? parsed : Date.now();
}

function createEvent(type, payload, cwd, options = {}) {
  const context = ensureSessionContext(cwd);
  return {
    v: 1,
    id: randomUUID(),
    ts: options.ts ?? Date.now(),
    engine: 'copilot',
    session_id: session.sessionId,
    project_hash: context.project.hash,
    cwd: context.repoRoot,
    ...(options.caps ? { caps: options.caps } : {}),
    type,
    payload,
  };
}

function normalizeWriteTarget(cwd, target) {
  const resolved = resolve(cwd, target);
  return existsSync(resolved) ? realpathSync.native(resolved) : resolved;
}

function extractStringArray(value) {
  return Array.isArray(value) ? value.filter((entry) => typeof entry === 'string') : [];
}

function extractWriteTargets(toolName, toolArgs, cwd) {
  const normalizedToolName = String(toolName || '').trim().toLowerCase();
  if (
    normalizedToolName &&
    !['create', 'edit', 'multiedit', 'write', 'apply_patch'].some((name) =>
      normalizedToolName.includes(name),
    )
  ) {
    return undefined;
  }

  const input = toolArgs && typeof toolArgs === 'object' && !Array.isArray(toolArgs) ? toolArgs : {};
  const candidates = new Set();
  for (const key of ['file_path', 'filePath', 'path', 'destination', 'target']) {
    const value = input[key];
    if (typeof value === 'string' && value.trim()) {
      candidates.add(normalizeWriteTarget(cwd, value));
    }
  }
  for (const key of ['paths', 'file_paths', 'files']) {
    for (const value of extractStringArray(input[key])) {
      if (value.trim()) {
        candidates.add(normalizeWriteTarget(cwd, value));
      }
    }
  }
  return candidates.size > 0 ? [...candidates] : undefined;
}

function safeStableStringify(value) {
  try {
    return JSON.stringify(value);
  } catch {
    return String(value);
  }
}

function permissionKey(request) {
  return String(request.kind || 'unknown') + ':' + String(request.toolCallId || '') + ':' + safeStableStringify(request);
}

function describePermissionRequest(request, toolName) {
  switch (request.kind) {
    case 'shell':
      return {
        title: request.intention || toolName || 'Shell command',
        details: request.fullCommandText,
      };
    case 'write':
      return {
        title: request.fileName || toolName || 'File write',
        details: request.intention,
      };
    case 'read':
      return {
        title: request.fileName || toolName || 'File read',
        details: request.intention,
      };
    case 'url':
      return {
        title: request.url || toolName || 'URL access',
        details: request.url,
      };
    case 'custom-tool':
      return {
        title: request.toolName || toolName || 'Custom tool',
        details: request.description,
      };
    default:
      return {
        title: toolName || request.kind,
        details: undefined,
      };
  }
}

function getOrCreatePendingEntry(request) {
  const key = permissionKey(request);
  const existing = (pendingByKey.get(key) || []).find((entry) => !entry.closed);
  if (existing) return existing;
  const entry = {
    key,
    request,
    requestId: null,
    toolCallId: request.toolCallId,
    toolName: request.toolCallId ? toolCalls.get(request.toolCallId)?.toolName : undefined,
    title: undefined,
    details: undefined,
    waiting: null,
    closed: false,
  };
  const next = pendingByKey.get(key) || [];
  next.push(entry);
  pendingByKey.set(key, next);
  return entry;
}

function removePendingEntry(entry) {
  if (entry.requestId) {
    pendingByRequestId.delete(entry.requestId);
  }
  const list = pendingByKey.get(entry.key) || [];
  const next = list.filter((candidate) => candidate !== entry);
  if (next.length === 0) pendingByKey.delete(entry.key);
  else pendingByKey.set(entry.key, next);
}

function finalizePendingEntry(entry, outcome, reason) {
  if (!entry || entry.closed) return;
  entry.closed = true;
  if (entry.waiting) {
    entry.waiting({ kind: 'no-result' });
    entry.waiting = null;
  }
  if (entry.requestId) {
    emitEvent(
      createEvent('permission_resolved', {
        request_id: entry.requestId,
        outcome,
        ...(reason ? { reason } : {}),
      }, sessionContext?.repoRoot ?? process.cwd()),
    );
  }
  removePendingEntry(entry);
}

function queueInjectContext(text, options = {}) {
  const normalized = String(text || '').trim();
  if (!normalized) return;
  pruneInjectQueue();
  while (injectQueue.length >= MAX_INJECT_NOTES) {
    injectQueue.shift();
    if (!options.silent) {
      emitEvent(createEvent('meta', { kind: 'inject_context_dropped', reason: 'queue_full' }, sessionContext?.repoRoot ?? process.cwd()));
    }
  }
  injectQueue.push({
    text: normalized,
    expiresAt: Date.now() + INJECT_TTL_MS,
  });
  if (!options.silent) {
    emitEvent(createEvent('meta', { kind: 'inject_context_queued' }, sessionContext?.repoRoot ?? process.cwd()));
  }
}

function pruneInjectQueue() {
  const now = Date.now();
  while (injectQueue.length > 0 && injectQueue[0].expiresAt <= now) {
    injectQueue.shift();
    emitEvent(createEvent('meta', { kind: 'inject_context_expired' }, sessionContext?.repoRoot ?? process.cwd(), { ts: now }));
  }
}

function consumeInjectContext() {
  pruneInjectQueue();
  const next = injectQueue.shift();
  if (!next) return undefined;
  emitEvent(createEvent('meta', { kind: 'inject_context_consumed' }, sessionContext?.repoRoot ?? process.cwd()));
  return next.text;
}

function emitEvent(event) {
  bridgeQueue.push(event);
  while (bridgeQueue.length > MAX_QUEUED_EVENTS) {
    bridgeQueue.shift();
  }
  void ensureBridgeConnection(event.cwd);
}

function flushBridgeQueue() {
  if (!bridgeSocket || bridgeSocket.readyState !== WebSocket.OPEN) return;
  while (bridgeQueue.length > 0) {
    const event = bridgeQueue.shift();
    bridgeSocket.send(JSON.stringify({ type: 'publish_event', event }));
  }
}

function syncOpenPendings() {
  const cwd = sessionContext?.repoRoot ?? process.cwd();
  for (const entry of pendingByRequestId.values()) {
    if (!entry.closed && entry.requestId) {
      emitEvent(
        createEvent('permission_pending', {
          request_id: entry.requestId,
          permission_kind: entry.request.kind,
          ...(entry.toolCallId ? { tool_call_id: entry.toolCallId } : {}),
          ...(entry.toolName ? { tool_name: entry.toolName } : {}),
          ...(entry.title ? { title: entry.title } : {}),
          ...(entry.details ? { details: entry.details } : {}),
        }, cwd),
      );
    }
  }
}

function scheduleReconnect(cwd) {
  if (reconnectTimer) return;
  reconnectTimer = setTimeout(() => {
    reconnectTimer = null;
    void ensureBridgeConnection(cwd);
  }, 2000);
}

async function executeControlTool(toolName, input, cwd) {
  if (toolName !== 'holdpoint_dry_run') {
    emitEvent(createEvent('meta', { kind: 'trigger_tool_rejected', tool_name: toolName }, cwd));
    return;
  }
  const note = typeof input?.note === 'string' && input.note.trim() ? input.note.trim() : 'no note';
  queueInjectContext('Holdpoint tool holdpoint_dry_run result: ' + note, { silent: true });
  emitEvent(createEvent('meta', { kind: 'trigger_tool_completed', tool_name: toolName }, cwd));
}

async function handleControlCommand(command, cwd) {
  switch (command.command) {
    case 'approve_pending': {
      const entry = pendingByRequestId.get(command.args.request_id);
      if (!entry || entry.closed || !entry.waiting) {
        emitEvent(createEvent('meta', { kind: 'control_rejected', command: command.command }, cwd));
        return;
      }
      entry.waiting({ kind: 'approve-once' });
      entry.waiting = null;
      return;
    }
    case 'deny_pending': {
      const entry = pendingByRequestId.get(command.args.request_id);
      if (!entry || entry.closed || !entry.waiting) {
        emitEvent(createEvent('meta', { kind: 'control_rejected', command: command.command }, cwd));
        return;
      }
      entry.waiting({
        kind: 'reject',
        ...(command.args.reason ? { feedback: command.args.reason } : {}),
      });
      entry.waiting = null;
      return;
    }
    case 'inject_context':
      queueInjectContext(command.args.text);
      return;
    case 'trigger_tool':
      await executeControlTool(command.args.tool_name, command.args.input || {}, cwd);
      return;
  }
}

async function ensureBridgeConnection(cwd) {
  if (typeof WebSocket !== 'function') {
    if (!warnedMissingWebSocket && session) {
      warnedMissingWebSocket = true;
      await session.log('Holdpoint Live control is unavailable because WebSocket is not supported in this runtime.', {
        level: 'warning',
      });
    }
    return;
  }

  const context = ensureSessionContext(cwd);
  if (bridgeSocket && (bridgeSocket.readyState === WebSocket.OPEN || bridgeSocket.readyState === WebSocket.CONNECTING)) {
    return;
  }

  const lock = readDaemonLock();
  if (!lock) {
    scheduleReconnect(context.repoRoot);
    return;
  }

  bridgeSocket = new WebSocket('ws://127.0.0.1:' + lock.port + '/v1/stream', ['holdpoint-' + lock.token]);
  bridgeSocket.addEventListener('open', () => {
    warnedMissingWebSocket = false;
    flushBridgeQueue();
    bridgeSocket?.send(JSON.stringify({ type: 'register_control', session_key: context.sessionKey }));
    syncOpenPendings();
    flushBridgeQueue();
  });
  bridgeSocket.addEventListener('message', (message) => {
    let parsed;
    try {
      parsed = JSON.parse(String(message.data));
    } catch {
      return;
    }
    if (parsed?.type === 'control' && parsed.session_key === context.sessionKey) {
      void handleControlCommand(parsed.command, context.repoRoot);
    }
  });
  bridgeSocket.addEventListener('close', () => {
    bridgeSocket = null;
    scheduleReconnect(context.repoRoot);
  });
  bridgeSocket.addEventListener('error', () => {});
}

async function drainBridgeQueue(timeoutMs = 250) {
  const deadline = Date.now() + timeoutMs;
  while (bridgeQueue.length > 0 && Date.now() < deadline) {
    flushBridgeQueue();
    await new Promise((resolvePromise) => setTimeout(resolvePromise, 10));
  }
}

const tools = [
  {
    name: 'holdpoint_dry_run',
    description: 'Reference Holdpoint control tool that echoes an optional note.',
    skipPermission: true,
    parameters: {
      type: 'object',
      properties: {
        note: { type: 'string', description: 'Optional text to echo back.' },
      },
    },
    handler: async (args) => {
      const note = typeof args?.note === 'string' && args.note.trim() ? args.note.trim() : 'no note';
      return {
        textResultForLlm: 'Holdpoint dry run completed: ' + note,
        resultType: 'success',
      };
    },
  },
];

session = await joinSession({
  tools,
  onPermissionRequest: async (request) => {
    const entry = getOrCreatePendingEntry(request);
    await ensureBridgeConnection(sessionContext?.repoRoot ?? process.cwd());
    return await new Promise((resolvePromise) => {
      entry.waiting = resolvePromise;
      setTimeout(() => {
        if (entry.waiting === resolvePromise) {
          entry.waiting = null;
          resolvePromise({ kind: 'no-result' });
        }
      }, PERMISSION_TIMEOUT_MS);
    });
  },
  hooks: {
    onSessionStart: async (input) => {
      const context = ensureSessionContext(input.cwd);
      emitEvent(
        createEvent(
          'session_start',
          {
            source: input.source === 'resume' ? 'resume' : 'startup',
            tools_available: ['holdpoint_dry_run'],
          },
          context.repoRoot,
          { caps: LIVE_CAPS, ts: toTs(input.timestamp) },
        ),
      );
      await ensureBridgeConnection(context.repoRoot);
      const addendum = gatherHookContext(context.repoRoot, 'session_start');
      if (addendum?.truncated) {
        emitEvent(
          createEvent(
            'meta',
            {
              kind: 'context_truncated',
              original_length: addendum.originalLength,
              emitted_length: addendum.emittedLength,
            },
            context.repoRoot,
          ),
        );
      }
      return addendum ? { additionalContext: addendum.additionalContext } : undefined;
    },
    onSessionEnd: async (input) => {
      const cwd = sessionContext?.repoRoot ?? input.cwd ?? process.cwd();
      for (const entries of [...pendingByKey.values()]) {
        for (const entry of entries) {
          finalizePendingEntry(entry, 'session_ended');
        }
      }
      emitEvent(
        createEvent(
          'session_end',
          {
            reason: input.reason === 'error' ? 'error' : input.reason === 'user_exit' ? 'user' : 'completed',
          },
          cwd,
          { ts: toTs(input.timestamp) },
        ),
      );
      await drainBridgeQueue();
    },
    onUserPromptSubmitted: async (input) => {
      const cwd = ensureSessionContext(input.cwd).repoRoot;
      emitEvent(
        createEvent(
          'prompt_submit',
          {
            prompt: input.prompt,
          },
          cwd,
          { ts: toTs(input.timestamp) },
        ),
      );
      // Combine configured message_submit context (inject/prompt checks +
      // datetime) with any live-control note queued from the dashboard.
      const hookContext = gatherHookContext(cwd, 'message_submit');
      const injected = consumeInjectContext();
      const segments = [hookContext?.additionalContext, injected].filter(Boolean);
      return segments.length ? { additionalContext: segments.join('\n\n') } : undefined;
    },
    onPreToolUse: async (input) => {
      const repoRoot = ensureSessionContext(input.cwd).repoRoot;
      if (input.toolName === 'task_complete') {
        await session.log('Holdpoint: running checks\u2026', { ephemeral: true });
        emitEvent(createEvent('meta', { kind: 'copilot_task_complete_check_started' }, repoRoot));
        const result = runHoldpointChecks(repoRoot);
        if (!result.ok) {
          emitEvent(
            createEvent(
              'stop_block',
              {
                reason: result.output,
                failing_checks: [],
              },
              repoRoot,
            ),
          );
          await drainBridgeQueue();
          return {
            permissionDecision: 'deny',
            permissionDecisionReason: result.output,
          };
        }
        emitEvent(createEvent('stop_pass', { duration_ms: result.durationMs }, repoRoot));
        await drainBridgeQueue();
        return;
      }

      // before_tool gate: run cmd checks bound to before_tool; deny on failure.
      if (hasCmdAt(repoRoot, 'before_tool')) {
        const result = runHoldpointChecks(repoRoot, "node_modules/.bin/holdpoint check --staged --hook before_tool");
        if (!result.ok) {
          emitEvent(createEvent('tool_failure', { tool_name: input.toolName, tool_use_id: input.toolCallId || 'before_tool', error: result.output }, repoRoot));
          await drainBridgeQueue();
          return { permissionDecision: 'deny', permissionDecisionReason: result.output };
        }
      }

      const additionalContext = consumeInjectContext();
      return additionalContext ? { additionalContext } : undefined;
    },
  },
});

session.on('tool.execution_start', (event) => {
  const cwd = ensureSessionContext(process.cwd()).repoRoot;
  const writeTargets = extractWriteTargets(event.data.toolName, event.data.arguments || {}, cwd);
  toolCalls.set(event.data.toolCallId, {
    toolName: event.data.toolName,
    toolArgs: event.data.arguments || {},
    startedAt: toTs(event.timestamp),
    writeTargets,
  });
  emitEvent(
    createEvent(
      'tool_pre',
      {
        tool_name: event.data.toolName,
        tool_use_id: event.data.toolCallId,
        tool_input: event.data.arguments || {},
        ...(writeTargets ? { write_targets: writeTargets } : {}),
      },
      cwd,
      { ts: toTs(event.timestamp) },
    ),
  );
});

session.on('tool.execution_complete', (event) => {
  const cwd = ensureSessionContext(process.cwd()).repoRoot;
  const current = toolCalls.get(event.data.toolCallId);
  const durationMs = Math.max(0, toTs(event.timestamp) - (current?.startedAt || toTs(event.timestamp)));
  const writeTargets = current?.writeTargets;
  if (event.data.success) {
    emitEvent(
      createEvent(
        'tool_post',
        {
          tool_name: current?.toolName || 'unknown',
          tool_use_id: event.data.toolCallId,
          success: true,
          duration_ms: durationMs,
          ...(writeTargets ? { write_targets: writeTargets } : {}),
        },
        cwd,
        { ts: toTs(event.timestamp) },
      ),
    );
  } else {
    emitEvent(
      createEvent(
        'tool_failure',
        {
          tool_name: current?.toolName || 'unknown',
          tool_use_id: event.data.toolCallId,
          error: event.data.error?.message || 'Tool execution failed',
        },
        cwd,
        { ts: toTs(event.timestamp) },
      ),
    );
  }
  toolCalls.delete(event.data.toolCallId);
});

session.on('permission.requested', (event) => {
  if (event.data.resolvedByHook) {
    emitEvent(
      createEvent(
        'permission_resolved',
        {
          request_id: event.data.requestId,
          outcome: 'resolved_by_hook',
        },
        sessionContext?.repoRoot ?? process.cwd(),
        { ts: toTs(event.timestamp) },
      ),
    );
    return;
  }

  const entry = getOrCreatePendingEntry(event.data.permissionRequest);
  entry.requestId = event.data.requestId;
  entry.toolCallId = entry.toolCallId || event.data.toolCallId;
  entry.toolName = entry.toolName || (entry.toolCallId ? toolCalls.get(entry.toolCallId)?.toolName : undefined);
  const description = describePermissionRequest(event.data.permissionRequest, entry.toolName);
  entry.title = description.title;
  entry.details = description.details;
  pendingByRequestId.set(event.data.requestId, entry);
  emitEvent(
    createEvent(
      'permission_pending',
      {
        request_id: event.data.requestId,
        permission_kind: event.data.permissionRequest.kind,
        ...(entry.toolCallId ? { tool_call_id: entry.toolCallId } : {}),
        ...(entry.toolName ? { tool_name: entry.toolName } : {}),
        ...(entry.title ? { title: entry.title } : {}),
        ...(entry.details ? { details: entry.details } : {}),
      },
      sessionContext?.repoRoot ?? process.cwd(),
      { ts: toTs(event.timestamp) },
    ),
  );
});

session.on('permission.completed', (event) => {
  const entry = pendingByRequestId.get(event.data.requestId);
  if (!entry) return;
  switch (event.data.result.kind) {
    case 'approved':
    case 'approved-for-session':
    case 'approved-for-location':
      finalizePendingEntry(entry, 'approved');
      break;
    default:
      finalizePendingEntry(entry, 'denied');
      break;
  }
});
