#!/usr/bin/env node
// AUTO-GENERATED by @holdpoint/engine-copilot — do not edit manually.
// sessionStart hook: injects session_context_files as additionalContext.
// task_complete interception is handled by extension.mjs, not this script.

import { execSync } from "node:child_process";
import { existsSync, readFileSync } from "node:fs";
import { join, resolve, sep } from "node:path";

function resolveRepoRoot(cwd) {
  try {
    return execSync("git rev-parse --show-toplevel", {
      encoding: "utf8",
      stdio: ["pipe", "pipe", "ignore"],
      cwd: cwd ?? process.cwd(),
    }).trim();
  } catch {
    return cwd ?? process.cwd();
  }
}

let input = {};
try {
  const raw = readFileSync(0 /* stdin fd */, "utf8").trim();
  if (raw) input = JSON.parse(raw);
} catch { /* non-JSON or empty stdin */ }

const repoRoot = resolveRepoRoot(input.cwd);

try {
  const configPath = join(repoRoot, ".github/holdpoint/generated/checks.immutable.json");
  if (!existsSync(configPath)) {
    process.stderr.write("[holdpoint] checks.immutable.json not found — skipping context injection\n");
    process.exit(0);
  }
  const config = JSON.parse(readFileSync(configPath, "utf8"));
  const files = Array.isArray(config.session_context_files) ? config.session_context_files : [];
  const parts = [];
  for (const file of files) {
    if (typeof file !== "string" || !file.trim()) continue;
    const abs = resolve(repoRoot, file);
    if (!abs.startsWith(repoRoot + sep) && abs !== repoRoot) {
      process.stderr.write(`[holdpoint] Skipping unsafe path: ${file}\n`);
      continue;
    }
    if (!existsSync(abs)) {
      process.stderr.write(`[holdpoint] session_context_file not found (skipping): ${file}\n`);
      continue;
    }
    try {
      parts.push(`<!-- ${file} -->\n${readFileSync(abs, "utf8")}`);
    } catch (e) {
      process.stderr.write(`[holdpoint] Failed to read ${file}: ${e.message}\n`);
    }
  }
  if (parts.length > 0) {
    process.stdout.write(JSON.stringify({ additionalContext: parts.join("\n\n") }));
  }
} catch (err) {
  process.stderr.write(`[holdpoint] sessionStart hook error: ${err instanceof Error ? err.message : String(err)}\n`);
}
process.exit(0);
