#!/usr/bin/env node
// AUTO-GENERATED by @holdpoint/engine-copilot — do not edit manually.
// Handles: sessionStart (context injection) and preToolUse/task_complete (check gating).

import { execSync } from "node:child_process";
import { existsSync, readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { join, resolve, sep } from "node:path";

const COMMIT_CACHE_MAX = 100;

function denyTaskComplete(reason) {
  process.stdout.write(JSON.stringify({ permissionDecision: "deny", permissionDecisionReason: reason }));
  process.exit(0);
}

function resolveRepoRoot(cwd) {
  try {
    return execSync("git rev-parse --show-toplevel", {
      encoding: "utf8",
      stdio: ["pipe", "pipe", "ignore"],
      cwd: cwd ?? process.cwd(),
    }).trim();
  } catch {
    return cwd ?? process.cwd();
  }
}

function getHeadSha(root) {
  try { return execSync("git rev-parse HEAD", { encoding: "utf8", stdio: ["pipe", "pipe", "ignore"], cwd: root }).trim(); }
  catch { return null; }
}

function readCommitCache(root) {
  try {
    const raw = readFileSync(join(root, ".holdpoint/checked-commits.json"), "utf8");
    const parsed = JSON.parse(raw);
    return new Set(Array.isArray(parsed.verified) ? parsed.verified : []);
  } catch { return new Set(); }
}

function recordCommitCache(root, sha) {
  try {
    const existing = readCommitCache(root);
    const updated = [sha, ...[...existing].filter((s) => s !== sha)].slice(0, COMMIT_CACHE_MAX);
    const dir = join(root, ".holdpoint");
    mkdirSync(dir, { recursive: true });
    writeFileSync(join(dir, "checked-commits.json"), JSON.stringify({ verified: updated }, null, 2) + "\n", "utf8");
  } catch { /* non-fatal */ }
}

// ── Parse stdin ───────────────────────────────────────────────────────────────

let input = {};
try {
  const raw = readFileSync(0 /* stdin fd */, "utf8").trim();
  if (raw) input = JSON.parse(raw);
} catch { /* non-JSON or empty stdin — treat as preToolUse */ }

const isSessionStart =
  typeof input.source === "string" &&
  ["startup", "resume", "new"].includes(input.source) &&
  !("toolName" in input) &&
  !("tool_name" in input);

const repoRoot = resolveRepoRoot(input.cwd);

// ── sessionStart: inject context files (fail-soft) ───────────────────────────

if (isSessionStart) {
  try {
    const configPath = join(repoRoot, ".github/holdpoint/generated/checks.immutable.json");
    if (!existsSync(configPath)) {
      process.stderr.write("[holdpoint] checks.immutable.json not found — skipping context injection\n");
      process.exit(0);
    }
    const config = JSON.parse(readFileSync(configPath, "utf8"));
    const files = Array.isArray(config.session_context_files) ? config.session_context_files : [];
    const parts = [];
    for (const file of files) {
      if (typeof file !== "string" || !file.trim()) continue;
      const abs = resolve(repoRoot, file);
      if (!abs.startsWith(repoRoot + sep) && abs !== repoRoot) {
        process.stderr.write(`[holdpoint] Skipping unsafe session_context_file path: ${file}\n`);
        continue;
      }
      if (!existsSync(abs)) {
        process.stderr.write(`[holdpoint] session_context_file not found (skipping): ${file}\n`);
        continue;
      }
      try {
        parts.push(`<!-- ${file} -->\n${readFileSync(abs, "utf8")}`);
      } catch (e) {
        process.stderr.write(`[holdpoint] Failed to read session_context_file ${file}: ${e.message}\n`);
      }
    }
    if (parts.length > 0) {
      process.stdout.write(JSON.stringify({ additionalContext: parts.join("\n\n") }));
    }
  } catch (err) {
    process.stderr.write(`[holdpoint] sessionStart hook error: ${err instanceof Error ? err.message : String(err)}\n`);
  }
  process.exit(0);
}

// ── preToolUse: run checks before task_complete (fail-closed) ────────────────

// Belt-and-suspenders guard — the matcher in holdpoint.json already limits this to task_complete
const toolName = input.toolName ?? input.tool_name ?? "";
if (toolName && toolName !== "task_complete") {
  process.exit(0);
}

try {
  function getStagedFiles() {
    try {
      return execSync("git diff --cached --name-only", {
        encoding: "utf8",
        stdio: ["pipe", "pipe", "ignore"],
        cwd: repoRoot,
      })
        .trim()
        .split("\n")
        .filter(Boolean);
    } catch {
      return [];
    }
  }

  function getLastCommitFiles() {
    try {
      return execSync("git diff --name-only HEAD~1 HEAD", {
        encoding: "utf8",
        stdio: ["pipe", "pipe", "ignore"],
        cwd: repoRoot,
      })
        .trim()
        .split("\n")
        .filter(Boolean);
    } catch {
      return [];
    }
  }

  function matchesWhen(when, changedFiles, userPatterns) {
    if (!when) return true;
    if (changedFiles.includes("__all__") || changedFiles.length === 0) return true;
    const patterns = {
      frontend: [
        /\.(tsx|jsx|css|scss)$/,
        /tailwind\.config\./,
        /postcss\.config\./,
        /^apps\/(builder|web)\//,
      ],
      backend: [
        /(^|\/)api\//,
        /(^|\/)server\//,
        /(^|\/)routes\//,
        /(^|\/)controllers\//,
        /(^|\/)middleware\//,
        /^packages\/[^/]+\/src\//,
      ],
      prisma: [/\.prisma$/, /(^|\/)prisma\//],
      socket: [/(^|\/)socket\//, /(^|\/)ws\//, /(^|\/)websocket\//],
      visual: [/\.stories\.(tsx?|jsx?)$/, /(^|\/)__screenshots__\//, /\.snap$/],
      python: [
        /\.pyi?$/,
        /requirements[^/]*\.txt$/,
        /pyproject\.toml$/,
        /setup\.(py|cfg)$/,
        /(^|\/)Pipfile(\.lock)?$/,
        /uv\.lock$/,
        /pytest\.ini$/,
        /tox\.ini$/,
      ],
      go: [/\.go$/, /go\.(mod|sum)$/],
      rust: [/\.rs$/, /Cargo\.(toml|lock)$/],
      java: [/\.(java|kt)$/, /\.gradle(\.kts)?$/, /pom\.xml$/],
      ruby: [/\.rb$/, /(^|\/)Gemfile(\.lock)?$/, /(^|\/)Rakefile$/],
      database: [
        /\.sql$/,
        /(^|\/)(migrations?|migration)\//,
        /(^|\/)prisma\//,
        /\.prisma$/,
        /(^|\/)db\//,
        /(^|\/)database\//,
        /(^|\/)(seeds?|seed)\//,
        /alembic\.ini$/,
      ],
      testing: [
        /\.(test|spec)\.(tsx?|jsx?|py|rb|go)$/,
        /(^|\/)__tests__\//,
        /(^|\/)tests?\//,
        /(^|\/)spec\//,
      ],
      infra: [
        /(^|\/)Dockerfile(\..*)?$/,
        /(^|\/)docker-compose/,
        /\.(tf|tfvars|hcl)$/,
        /(^|\/)k8s\//,
        /(^|\/)kubernetes\//,
        /(^|\/)(helm|charts)\//,
        /\.dockerignore$/,
      ],
      ci: [
        /(^|\/)(\.github\/workflows|\.circleci)\//,
        /(^|\/)Jenkinsfile$/,
        /(^|\/)\.(gitlab-ci|travis|drone)\.yml$/,
      ],
      docs: [/\.(mdx|rst)$/, /(^|\/)(docs|documentation)\//],
      structural: [
        /(^|\/|\\)package\.json$/,
        /tsconfig[^/]*\.json$/,
        /requirements[^/]*\.txt$/,
        /pyproject\.toml$/,
        /(^|\/)Pipfile(\.lock)?$/,
        /setup\.(py|cfg)$/,
        /pytest\.ini$/,
        /tox\.ini$/,
        /go\.mod$/,
        /Cargo\.toml$/,
        /pom\.xml$/,
        /build\.gradle(\.kts)?$/,
        /(^|\/)Gemfile(\.lock)?$/,
        /vitest\.config\./,
        /jest\.config\./,
        /playwright\.config\./,
        /eslint\.config\./,
        /\.eslintrc/,
        /biome\.json$/,
        /prettier\.config\./,
        /\.prettierrc/,
        /next\.config\./,
        /(^|\/)Dockerfile/,
        /(^|\/)docker-compose[^/]*\.(yml|yaml)$/,
        /\.tf$/,
        /prisma\/schema\.prisma$/,
        /openapi\.(yaml|yml|json)$/,
        /\.github\/workflows\/[^/]+\.(yml|yaml)$/,
        /(^|\/)(\.circleci\/|Jenkinsfile$|\.gitlab-ci\.yml$|\.travis\.yml$)/,
      ],
    };
    if (when in patterns) {
      return changedFiles.some((f) => (patterns[when] ?? []).some((re) => re.test(f)));
    }
    // User-defined named patterns
    if (userPatterns && when in userPatterns) {
      return changedFiles.some((f) => new RegExp(userPatterns[when]).test(f));
    }
    return changedFiles.some((f) => new RegExp(when).test(f));
  }

  function runCheck(check) {
    if (!check.cmd) return { status: "pending" };
    try {
      const output = execSync(check.cmd, {
        encoding: "utf8",
        timeout: 60000,
        stdio: "pipe",
        cwd: repoRoot,
      });
      return { status: "pass", output };
    } catch (e) {
      return {
        status: "fail",
        output: [e.stdout, e.stderr].filter(Boolean).join("\n"),
        exitCode: e.status ?? 1,
      };
    }
  }

  // Resolve effective file scope: staged → last commit → nothing (allow).
  // Use SHA cache to prevent re-checking the same commit on repeated task_complete calls.
  const stagedFiles = getStagedFiles();
  let changedFiles;
  let headSha = null;
  if (stagedFiles.length > 0) {
    changedFiles = stagedFiles;
  } else {
    headSha = getHeadSha(repoRoot);
    if (headSha && readCommitCache(repoRoot).has(headSha)) {
      process.exit(0); // already verified — allow
    }
    changedFiles = getLastCommitFiles();
    if (changedFiles.length === 0) {
      process.exit(0); // investigative session — allow
    }
  }

  // Re-sync if checks.yaml is staged
  if (changedFiles.some((f) => /^checks\.yaml$/.test(f))) {
    const sync = runCheck({ label: "Holdpoint sync", cmd: "npx holdpoint update" });
    if (sync.status === "fail") {
      denyTaskComplete(
        `Holdpoint: checks.yaml changed but \`holdpoint update\` failed:\n\n${(sync.output ?? "").trim()}\n\nFix the error above, then retry.`,
      );
    }
  }

  const configPath = join(repoRoot, ".github/holdpoint/generated/checks.immutable.json");
  if (!existsSync(configPath)) {
    denyTaskComplete("Holdpoint: .github/holdpoint/generated/checks.immutable.json not found — run: npx holdpoint update");
  }

  const config = JSON.parse(readFileSync(configPath, "utf8"));
  const failures = [];

  for (const check of config.checks.filter((c) => c.cmd !== undefined)) {
    if (!matchesWhen(check.when, changedFiles, config.patterns)) continue;
    const result = runCheck(check);
    if (result.status === "fail") failures.push({ check, result });
  }

  // Collect prompt checks so they can be included alongside cmd failures
  const promptChecks = config.checks.filter(
    (c) => c.prompt !== undefined && matchesWhen(c.when, changedFiles, config.patterns),
  );

  if (failures.length > 0) {
    const summary = failures
      .map((f) => `  ✗ [${f.check.label}]\n${(f.result.output ?? "").trim()}`)
      .join("\n\n");
    const promptSection =
      promptChecks.length > 0
        ? `\n\nComplete these actions before committing:\n${promptChecks.map((c) => `  □ [${c.label}] ${c.prompt ?? ""}`).join("\n")}`
        : "";
    denyTaskComplete(
      `Holdpoint: ${failures.length} check(s) failed:\n\n${summary}${promptSection}\n\nFix the above issues before marking the task complete.`,
    );
  }

  if (promptChecks.length > 0) {
    const list = promptChecks.map((c) => `  □ [${c.label}] ${c.prompt ?? ""}`).join("\n");
    process.stderr.write(`[holdpoint] Agent prompts to act on:\n${list}\n`);
  }

  // Record commit as verified so subsequent task_complete calls skip re-checking.
  if (headSha) recordCommitCache(repoRoot, headSha);

  // Allow — empty stdout = default allow
  process.exit(0);
} catch (err) {
  // Fail-closed: unexpected errors block task completion
  denyTaskComplete(`Holdpoint hook error: ${err instanceof Error ? err.message : String(err)}`);
}
