#!/usr/bin/env node
// AUTO-GENERATED by @sentinel/engine-copilot — do not edit manually.
// Handles: sessionStart (context injection) and preToolUse/task_complete (check gating).

import { execSync } from "node:child_process";
import { existsSync, readFileSync } from "node:fs";
import { join, resolve, sep } from "node:path";

function denyTaskComplete(reason) {
  process.stdout.write(JSON.stringify({ permissionDecision: "deny", permissionDecisionReason: reason }));
  process.exit(0);
}

function resolveRepoRoot(cwd) {
  try {
    return execSync("git rev-parse --show-toplevel", {
      encoding: "utf8",
      stdio: ["pipe", "pipe", "ignore"],
      cwd: cwd ?? process.cwd(),
    }).trim();
  } catch {
    return cwd ?? process.cwd();
  }
}

// ── Parse stdin ───────────────────────────────────────────────────────────────

let input = {};
try {
  const raw = readFileSync(0 /* stdin fd */, "utf8").trim();
  if (raw) input = JSON.parse(raw);
} catch { /* non-JSON or empty stdin — treat as preToolUse */ }

const isSessionStart =
  typeof input.source === "string" &&
  ["startup", "resume", "new"].includes(input.source) &&
  !("toolName" in input) &&
  !("tool_name" in input);

const repoRoot = resolveRepoRoot(input.cwd);

// ── sessionStart: inject context files (fail-soft) ───────────────────────────

if (isSessionStart) {
  try {
    const configPath = join(repoRoot, ".github/sentinel/generated/checks.immutable.json");
    if (!existsSync(configPath)) {
      process.stderr.write("[sentinel] checks.immutable.json not found — skipping context injection\n");
      process.exit(0);
    }
    const config = JSON.parse(readFileSync(configPath, "utf8"));
    const files = Array.isArray(config.session_context_files) ? config.session_context_files : [];
    const parts = [];
    for (const file of files) {
      if (typeof file !== "string" || !file.trim()) continue;
      const abs = resolve(repoRoot, file);
      if (!abs.startsWith(repoRoot + sep) && abs !== repoRoot) {
        process.stderr.write(`[sentinel] Skipping unsafe session_context_file path: ${file}\n`);
        continue;
      }
      if (!existsSync(abs)) {
        process.stderr.write(`[sentinel] session_context_file not found (skipping): ${file}\n`);
        continue;
      }
      try {
        parts.push(`<!-- ${file} -->\n${readFileSync(abs, "utf8")}`);
      } catch (e) {
        process.stderr.write(`[sentinel] Failed to read session_context_file ${file}: ${e.message}\n`);
      }
    }
    if (parts.length > 0) {
      process.stdout.write(JSON.stringify({ additionalContext: parts.join("\n\n") }));
    }
  } catch (err) {
    process.stderr.write(`[sentinel] sessionStart hook error: ${err instanceof Error ? err.message : String(err)}\n`);
  }
  process.exit(0);
}

// ── preToolUse: run checks before task_complete (fail-closed) ────────────────

// Belt-and-suspenders guard — the matcher in sentinel.json already limits this to task_complete
const toolName = input.toolName ?? input.tool_name ?? "";
if (toolName && toolName !== "task_complete") {
  process.exit(0);
}

try {
  function getStagedFiles() {
    try {
      return execSync("git diff --cached --name-only", {
        encoding: "utf8",
        stdio: ["pipe", "pipe", "ignore"],
        cwd: repoRoot,
      })
        .trim()
        .split("\n")
        .filter(Boolean);
    } catch {
      return [];
    }
  }

  function matchesWhen(when, changedFiles) {
    if (!when) return true;
    if (changedFiles.includes("__all__") || changedFiles.length === 0) return true;
    const patterns = {
      frontend: [
        /\.(tsx|jsx|css|scss)$/,
        /tailwind\.config\./,
        /postcss\.config\./,
        /^apps\/(builder|web)\//,
      ],
      backend: [
        /\/(api|server|routes|controllers|middleware)\//,
        /^packages\/[^/]+\/src\//,
      ],
      prisma: [/\.prisma$/, /\/prisma\//],
      socket: [/\/(socket|ws|websocket)\//],
      visual: [/\.stories\.(tsx?|jsx?)$/, /__screenshots__\//, /\.snap$/],
    };
    if (when in patterns) {
      return changedFiles.some((f) => (patterns[when] ?? []).some((re) => re.test(f)));
    }
    return changedFiles.some((f) => new RegExp(when).test(f));
  }

  function runCheck(check) {
    if (!check.cmd) return { status: "pending" };
    try {
      const output = execSync(check.cmd, {
        encoding: "utf8",
        timeout: 60000,
        stdio: "pipe",
        cwd: repoRoot,
      });
      return { status: "pass", output };
    } catch (e) {
      return {
        status: "fail",
        output: [e.stdout, e.stderr].filter(Boolean).join("\n"),
        exitCode: e.status ?? 1,
      };
    }
  }

  const changedFiles = getStagedFiles();

  // Re-sync if checks.yaml is staged
  if (changedFiles.some((f) => /^checks\.yaml$/.test(f))) {
    const sync = runCheck({ label: "Sentinel sync", cmd: "npx sentinel update" });
    if (sync.status === "fail") {
      denyTaskComplete(
        `Sentinel: checks.yaml changed but \`sentinel update\` failed:\n\n${(sync.output ?? "").trim()}\n\nFix the error above, then retry.`,
      );
    }
  }

  const configPath = join(repoRoot, ".github/sentinel/generated/checks.immutable.json");
  if (!existsSync(configPath)) {
    denyTaskComplete("Sentinel: .github/sentinel/generated/checks.immutable.json not found — run: npx sentinel update");
  }

  const config = JSON.parse(readFileSync(configPath, "utf8"));
  const failures = [];

  for (const check of config.checks.filter((c) => c.cmd !== undefined)) {
    if (!matchesWhen(check.when, changedFiles)) continue;
    const result = runCheck(check);
    if (result.status === "fail") failures.push({ check, result });
  }

  // Collect prompt checks so they can be included alongside cmd failures
  const promptChecks = config.checks.filter(
    (c) => c.prompt !== undefined && matchesWhen(c.when, changedFiles),
  );

  if (failures.length > 0) {
    const summary = failures
      .map((f) => `  ✗ [${f.check.label}]\n${(f.result.output ?? "").trim()}`)
      .join("\n\n");
    const promptSection =
      promptChecks.length > 0
        ? `\n\nComplete these actions before committing:\n${promptChecks.map((c) => `  □ [${c.label}] ${c.prompt ?? ""}`).join("\n")}`
        : "";
    denyTaskComplete(
      `Sentinel: ${failures.length} check(s) failed:\n\n${summary}${promptSection}\n\nFix the above issues before marking the task complete.`,
    );
  }

  if (promptChecks.length > 0) {
    const list = promptChecks.map((c) => `  □ [${c.label}] ${c.prompt ?? ""}`).join("\n");
    process.stderr.write(`[sentinel] Agent prompts to act on:\n${list}\n`);
  }

  // Allow — empty stdout = default allow
  process.exit(0);
} catch (err) {
  // Fail-closed: unexpected errors block task completion
  denyTaskComplete(`Sentinel hook error: ${err instanceof Error ? err.message : String(err)}`);
}
