import type { HoldpointConfig } from "@holdpoint/types";

/** Serialise a HoldpointConfig to checks.immutable.json at .github/holdpoint/generated/. */
export function buildConfigJson(config: HoldpointConfig): string {
  const withHeader: Record<string, unknown> = {
    "//": "AUTO-GENERATED — do not edit this file. Source of truth: checks.yaml. Regenerate: npx holdpoint update",
    ...(config as unknown as Record<string, unknown>),
  };
  return JSON.stringify(withHeader, null, 2) + "\n";
}

export function buildContextScript(): string {
  return `#!/usr/bin/env node
// AUTO-GENERATED by @holdpoint/engine-copilot — do not edit manually.
import { execSync } from 'node:child_process';
import { existsSync, readFileSync } from 'node:fs';
import { isAbsolute, join, relative, resolve } from 'node:path';

const MAX_CONTEXT_CHARS = 9000;

let input = {};
try {
  const raw = readFileSync(0, 'utf8').trim();
  if (raw) input = JSON.parse(raw);
} catch {}

function resolveRepoRoot(cwd) {
  try {
    return execSync('git rev-parse --show-toplevel', {
      encoding: 'utf8',
      stdio: ['pipe', 'pipe', 'ignore'],
      cwd: cwd ?? process.cwd(),
    }).trim();
  } catch {
    return cwd ?? process.cwd();
  }
}

function truncateText(value, maxChars) {
  const text = String(value || '');
  if (text.length <= maxChars) return { text, truncated: false, originalLength: text.length };
  return {
    text: text.slice(0, maxChars) + '\\n\\n[Holdpoint output truncated to ' + maxChars + ' chars.]',
    truncated: true,
    originalLength: text.length,
  };
}

function isPathInsideRoot(repoRoot, absPath) {
  const rel = relative(repoRoot, absPath);
  return rel === '' || (!rel.startsWith('..') && !isAbsolute(rel));
}

function readSessionContextAddendum(repoRoot) {
  const configPath = join(repoRoot, '.github/holdpoint/generated/checks.immutable.json');
  if (!existsSync(configPath)) return undefined;
  try {
    const config = JSON.parse(readFileSync(configPath, 'utf8'));
    const files = Array.isArray(config.session_context_files) ? config.session_context_files : [];
    const parts = [];
    for (const file of files) {
      if (typeof file !== 'string' || !file.trim()) continue;
      const abs = resolve(repoRoot, file);
      if (!isPathInsideRoot(repoRoot, abs)) continue;
      if (!existsSync(abs)) continue;
      try {
        parts.push('<!-- ' + file + ' -->\\n' + readFileSync(abs, 'utf8'));
      } catch {}
    }
    if (parts.length === 0) return undefined;
    const context = truncateText(parts.join('\\n\\n'), MAX_CONTEXT_CHARS);
    return {
      additionalContext: context.text,
      truncated: context.truncated,
      originalLength: context.originalLength,
      emittedLength: context.text.length,
    };
  } catch {
    return undefined;
  }
}

const root = resolveRepoRoot(typeof input.cwd === 'string' ? input.cwd : process.cwd());
const addendum = readSessionContextAddendum(root);
if (addendum?.additionalContext) {
  process.stdout.write(JSON.stringify({
    hookSpecificOutput: {
      hookEventName: typeof input.hook_event_name === 'string' ? input.hook_event_name : 'SessionStart',
      additionalContext: addendum.additionalContext,
    },
  }));
}
`;
}

/**
 * Generate .github/extensions/holdpoint/extension.mjs for the Copilot CLI local agent.
 *
 * Uses the @github/copilot-sdk/extension API (injected at runtime by the CLI — no install
 * needed). The extension handles both responsibilities in one place:
 *
 * onSessionStart — reads checks.immutable.json and injects session_context_files as
 *   additionalContext. Uses JSON (not YAML) because the extension is plain .mjs with no
 *   bundler — JSON.parse is native, a YAML parser is not.
 *
 * onPreToolUse — intercepts task_complete, delegates all check logic to the holdpoint CLI
 *   which reads checks.yaml, runs applicable checks, and surfaces prompt checks. Non-zero
 *   exit blocks task completion; Copilot stays in the agentic loop to fix issues.
 *
 * The check command defaults to `npx holdpoint check --staged`. Set
 * `engines.copilot.check_command` in checks.yaml to override.
 */
export function buildEngine(config?: HoldpointConfig): string {
  const checkCommand =
    config?.engines?.copilot?.check_command ?? "node_modules/.bin/holdpoint check --staged";
  const injectDatetime = config?.inject_datetime !== false;
  return `// AUTO-GENERATED by @holdpoint/engine-copilot — do not edit manually.

import { joinSession } from '@github/copilot-sdk/extension';
import { execFileSync, execSync } from 'node:child_process';
import { createHash, randomUUID } from 'node:crypto';
import { existsSync, readFileSync, realpathSync } from 'node:fs';
import { homedir } from 'node:os';
import { basename, isAbsolute, join, relative, resolve } from 'node:path';

const LIVE_CAPS = {
  can_stream: true,
  can_control: true,
  can_modify_context: true,
  can_register_tools: true,
  control_online: false,
};
const MAX_QUEUED_EVENTS = 200;
const MAX_INJECT_NOTES = 5;
const INJECT_TTL_MS = 5 * 60 * 1000;
const PERMISSION_TIMEOUT_MS = 60 * 1000;
const MAX_CONTEXT_CHARS = 9000;
const MAX_CHECK_OUTPUT_CHARS = 8000;
const CHECK_MAX_BUFFER_BYTES = 10 * 1024 * 1024;

let session;
let sessionContext = null;
let bridgeSocket = null;
let reconnectTimer = null;
let warnedMissingWebSocket = false;
const bridgeQueue = [];
const toolCalls = new Map();
const pendingByKey = new Map();
const pendingByRequestId = new Map();
const injectQueue = [];

function resolveHoldpointHome() {
  return resolve(process.env.HOLDPOINT_HOME || join(homedir(), '.holdpoint'));
}

function readDaemonLock() {
  const lockPath = join(resolveHoldpointHome(), 'daemon.lock');
  if (!existsSync(lockPath)) return null;
  try {
    const parsed = JSON.parse(readFileSync(lockPath, 'utf8'));
    if (
      typeof parsed.port === 'number' &&
      typeof parsed.token === 'string' &&
      typeof parsed.host === 'string'
    ) {
      return parsed;
    }
  } catch {}
  return null;
}

function resolveRepoRoot(cwd) {
  try {
    return execSync('git rev-parse --show-toplevel', {
      encoding: 'utf8',
      stdio: ['pipe', 'pipe', 'ignore'],
      cwd: cwd ?? process.cwd(),
    }).trim();
  } catch {
    return cwd ?? process.cwd();
  }
}

function sha12(value) {
  return createHash('sha256').update(value).digest('hex').slice(0, 12);
}

function identifyProject(cwd) {
  try {
    const root = realpathSync(
      execFileSync('git', ['rev-parse', '--show-toplevel'], {
        cwd,
        encoding: 'utf8',
        stdio: ['ignore', 'pipe', 'ignore'],
      }).trim(),
    );
    return { hash: sha12(root), name: basename(root), root };
  } catch {
    const root = realpathSync(cwd);
    return { hash: sha12(root), name: basename(root), root };
  }
}

function buildSessionKey(projectHash, sessionId) {
  return projectHash + ':copilot:' + sessionId;
}

function ensureSessionContext(cwd) {
  if (sessionContext) return sessionContext;
  const repoRoot = resolveRepoRoot(cwd ?? process.cwd());
  const project = identifyProject(repoRoot);
  sessionContext = {
    repoRoot,
    project,
    sessionKey: buildSessionKey(project.hash, session.sessionId),
  };
  return sessionContext;
}

function truncateText(value, maxChars) {
  const text = String(value || '');
  if (text.length <= maxChars) return { text, truncated: false, originalLength: text.length };
  return {
    text: text.slice(0, maxChars) + '\\n\\n[Holdpoint output truncated to ' + maxChars + ' chars.]',
    truncated: true,
    originalLength: text.length,
  };
}

function isPathInsideRoot(repoRoot, absPath) {
  const rel = relative(repoRoot, absPath);
  return rel === '' || (!rel.startsWith('..') && !isAbsolute(rel));
}

function readSessionContextAddendum(repoRoot) {
  const configPath = join(repoRoot, '.github/holdpoint/generated/checks.immutable.json');
  if (!existsSync(configPath)) return undefined;
  try {
    const config = JSON.parse(readFileSync(configPath, 'utf8'));
    const files = Array.isArray(config.session_context_files) ? config.session_context_files : [];
    const parts = [];
    for (const file of files) {
      if (typeof file !== 'string' || !file.trim()) continue;
      const abs = resolve(repoRoot, file);
      if (!isPathInsideRoot(repoRoot, abs)) continue;
      if (!existsSync(abs)) continue;
      try {
        parts.push('<!-- ' + file + ' -->\\n' + readFileSync(abs, 'utf8'));
      } catch {}
    }
    if (parts.length === 0) return undefined;
    const context = truncateText(parts.join('\\n\\n'), MAX_CONTEXT_CHARS);
    return {
      additionalContext: context.text,
      truncated: context.truncated,
      originalLength: context.originalLength,
      emittedLength: context.text.length,
    };
  } catch {
    return undefined;
  }
}

function runHoldpointChecks(repoRoot) {
  const startedAt = Date.now();
  try {
    const output = execSync(${JSON.stringify(checkCommand)}, {
      cwd: repoRoot,
      stdio: 'pipe',
      encoding: 'utf8',
      maxBuffer: CHECK_MAX_BUFFER_BYTES,
    });
    return {
      ok: true,
      durationMs: Date.now() - startedAt,
      output: String(output || '').trim(),
    };
  } catch (error) {
    const output = [error && error.stdout, error && error.stderr, error && error.message]
      .filter(Boolean)
      .join('\\n')
      .trim();
    const truncated = truncateText(output, MAX_CHECK_OUTPUT_CHARS);
    return {
      ok: false,
      durationMs: Date.now() - startedAt,
      output: truncated.text || 'Holdpoint checks failed. Fix the issues above, then re-attempt.',
      truncated: truncated.truncated,
      originalLength: truncated.originalLength,
    };
  }
}

function toTs(value) {
  if (typeof value === 'number' && Number.isFinite(value)) return value;
  const parsed = Date.parse(String(value ?? ''));
  return Number.isFinite(parsed) ? parsed : Date.now();
}

function createEvent(type, payload, cwd, options = {}) {
  const context = ensureSessionContext(cwd);
  return {
    v: 1,
    id: randomUUID(),
    ts: options.ts ?? Date.now(),
    engine: 'copilot',
    session_id: session.sessionId,
    project_hash: context.project.hash,
    cwd: context.repoRoot,
    ...(options.caps ? { caps: options.caps } : {}),
    type,
    payload,
  };
}

function normalizeWriteTarget(cwd, target) {
  const resolved = resolve(cwd, target);
  return existsSync(resolved) ? realpathSync.native(resolved) : resolved;
}

function extractStringArray(value) {
  return Array.isArray(value) ? value.filter((entry) => typeof entry === 'string') : [];
}

function extractWriteTargets(toolName, toolArgs, cwd) {
  const normalizedToolName = String(toolName || '').trim().toLowerCase();
  if (
    normalizedToolName &&
    !['create', 'edit', 'multiedit', 'write', 'apply_patch'].some((name) =>
      normalizedToolName.includes(name),
    )
  ) {
    return undefined;
  }

  const input = toolArgs && typeof toolArgs === 'object' && !Array.isArray(toolArgs) ? toolArgs : {};
  const candidates = new Set();
  for (const key of ['file_path', 'filePath', 'path', 'destination', 'target']) {
    const value = input[key];
    if (typeof value === 'string' && value.trim()) {
      candidates.add(normalizeWriteTarget(cwd, value));
    }
  }
  for (const key of ['paths', 'file_paths', 'files']) {
    for (const value of extractStringArray(input[key])) {
      if (value.trim()) {
        candidates.add(normalizeWriteTarget(cwd, value));
      }
    }
  }
  return candidates.size > 0 ? [...candidates] : undefined;
}

function safeStableStringify(value) {
  try {
    return JSON.stringify(value);
  } catch {
    return String(value);
  }
}

function permissionKey(request) {
  return String(request.kind || 'unknown') + ':' + String(request.toolCallId || '') + ':' + safeStableStringify(request);
}

function describePermissionRequest(request, toolName) {
  switch (request.kind) {
    case 'shell':
      return {
        title: request.intention || toolName || 'Shell command',
        details: request.fullCommandText,
      };
    case 'write':
      return {
        title: request.fileName || toolName || 'File write',
        details: request.intention,
      };
    case 'read':
      return {
        title: request.fileName || toolName || 'File read',
        details: request.intention,
      };
    case 'url':
      return {
        title: request.url || toolName || 'URL access',
        details: request.url,
      };
    case 'custom-tool':
      return {
        title: request.toolName || toolName || 'Custom tool',
        details: request.description,
      };
    default:
      return {
        title: toolName || request.kind,
        details: undefined,
      };
  }
}

function getOrCreatePendingEntry(request) {
  const key = permissionKey(request);
  const existing = (pendingByKey.get(key) || []).find((entry) => !entry.closed);
  if (existing) return existing;
  const entry = {
    key,
    request,
    requestId: null,
    toolCallId: request.toolCallId,
    toolName: request.toolCallId ? toolCalls.get(request.toolCallId)?.toolName : undefined,
    title: undefined,
    details: undefined,
    waiting: null,
    closed: false,
  };
  const next = pendingByKey.get(key) || [];
  next.push(entry);
  pendingByKey.set(key, next);
  return entry;
}

function removePendingEntry(entry) {
  if (entry.requestId) {
    pendingByRequestId.delete(entry.requestId);
  }
  const list = pendingByKey.get(entry.key) || [];
  const next = list.filter((candidate) => candidate !== entry);
  if (next.length === 0) pendingByKey.delete(entry.key);
  else pendingByKey.set(entry.key, next);
}

function finalizePendingEntry(entry, outcome, reason) {
  if (!entry || entry.closed) return;
  entry.closed = true;
  if (entry.waiting) {
    entry.waiting({ kind: 'no-result' });
    entry.waiting = null;
  }
  if (entry.requestId) {
    emitEvent(
      createEvent('permission_resolved', {
        request_id: entry.requestId,
        outcome,
        ...(reason ? { reason } : {}),
      }, sessionContext?.repoRoot ?? process.cwd()),
    );
  }
  removePendingEntry(entry);
}

function queueInjectContext(text, options = {}) {
  const normalized = String(text || '').trim();
  if (!normalized) return;
  pruneInjectQueue();
  while (injectQueue.length >= MAX_INJECT_NOTES) {
    injectQueue.shift();
    if (!options.silent) {
      emitEvent(createEvent('meta', { kind: 'inject_context_dropped', reason: 'queue_full' }, sessionContext?.repoRoot ?? process.cwd()));
    }
  }
  injectQueue.push({
    text: normalized,
    expiresAt: Date.now() + INJECT_TTL_MS,
  });
  if (!options.silent) {
    emitEvent(createEvent('meta', { kind: 'inject_context_queued' }, sessionContext?.repoRoot ?? process.cwd()));
  }
}

function pruneInjectQueue() {
  const now = Date.now();
  while (injectQueue.length > 0 && injectQueue[0].expiresAt <= now) {
    injectQueue.shift();
    emitEvent(createEvent('meta', { kind: 'inject_context_expired' }, sessionContext?.repoRoot ?? process.cwd(), { ts: now }));
  }
}

function consumeInjectContext() {
  pruneInjectQueue();
  const next = injectQueue.shift();
  if (!next) return undefined;
  emitEvent(createEvent('meta', { kind: 'inject_context_consumed' }, sessionContext?.repoRoot ?? process.cwd()));
  return next.text;
}

function emitEvent(event) {
  bridgeQueue.push(event);
  while (bridgeQueue.length > MAX_QUEUED_EVENTS) {
    bridgeQueue.shift();
  }
  void ensureBridgeConnection(event.cwd);
}

function flushBridgeQueue() {
  if (!bridgeSocket || bridgeSocket.readyState !== WebSocket.OPEN) return;
  while (bridgeQueue.length > 0) {
    const event = bridgeQueue.shift();
    bridgeSocket.send(JSON.stringify({ type: 'publish_event', event }));
  }
}

function syncOpenPendings() {
  const cwd = sessionContext?.repoRoot ?? process.cwd();
  for (const entry of pendingByRequestId.values()) {
    if (!entry.closed && entry.requestId) {
      emitEvent(
        createEvent('permission_pending', {
          request_id: entry.requestId,
          permission_kind: entry.request.kind,
          ...(entry.toolCallId ? { tool_call_id: entry.toolCallId } : {}),
          ...(entry.toolName ? { tool_name: entry.toolName } : {}),
          ...(entry.title ? { title: entry.title } : {}),
          ...(entry.details ? { details: entry.details } : {}),
        }, cwd),
      );
    }
  }
}

function scheduleReconnect(cwd) {
  if (reconnectTimer) return;
  reconnectTimer = setTimeout(() => {
    reconnectTimer = null;
    void ensureBridgeConnection(cwd);
  }, 2000);
}

async function executeControlTool(toolName, input, cwd) {
  if (toolName !== 'holdpoint_dry_run') {
    emitEvent(createEvent('meta', { kind: 'trigger_tool_rejected', tool_name: toolName }, cwd));
    return;
  }
  const note = typeof input?.note === 'string' && input.note.trim() ? input.note.trim() : 'no note';
  queueInjectContext('Holdpoint tool holdpoint_dry_run result: ' + note, { silent: true });
  emitEvent(createEvent('meta', { kind: 'trigger_tool_completed', tool_name: toolName }, cwd));
}

async function handleControlCommand(command, cwd) {
  switch (command.command) {
    case 'approve_pending': {
      const entry = pendingByRequestId.get(command.args.request_id);
      if (!entry || entry.closed || !entry.waiting) {
        emitEvent(createEvent('meta', { kind: 'control_rejected', command: command.command }, cwd));
        return;
      }
      entry.waiting({ kind: 'approve-once' });
      entry.waiting = null;
      return;
    }
    case 'deny_pending': {
      const entry = pendingByRequestId.get(command.args.request_id);
      if (!entry || entry.closed || !entry.waiting) {
        emitEvent(createEvent('meta', { kind: 'control_rejected', command: command.command }, cwd));
        return;
      }
      entry.waiting({
        kind: 'reject',
        ...(command.args.reason ? { feedback: command.args.reason } : {}),
      });
      entry.waiting = null;
      return;
    }
    case 'inject_context':
      queueInjectContext(command.args.text);
      return;
    case 'trigger_tool':
      await executeControlTool(command.args.tool_name, command.args.input || {}, cwd);
      return;
  }
}

async function ensureBridgeConnection(cwd) {
  if (typeof WebSocket !== 'function') {
    if (!warnedMissingWebSocket && session) {
      warnedMissingWebSocket = true;
      await session.log('Holdpoint Live control is unavailable because WebSocket is not supported in this runtime.', {
        level: 'warning',
      });
    }
    return;
  }

  const context = ensureSessionContext(cwd);
  if (bridgeSocket && (bridgeSocket.readyState === WebSocket.OPEN || bridgeSocket.readyState === WebSocket.CONNECTING)) {
    return;
  }

  const lock = readDaemonLock();
  if (!lock) {
    scheduleReconnect(context.repoRoot);
    return;
  }

  bridgeSocket = new WebSocket('ws://127.0.0.1:' + lock.port + '/v1/stream', ['holdpoint-' + lock.token]);
  bridgeSocket.addEventListener('open', () => {
    warnedMissingWebSocket = false;
    flushBridgeQueue();
    bridgeSocket?.send(JSON.stringify({ type: 'register_control', session_key: context.sessionKey }));
    syncOpenPendings();
    flushBridgeQueue();
  });
  bridgeSocket.addEventListener('message', (message) => {
    let parsed;
    try {
      parsed = JSON.parse(String(message.data));
    } catch {
      return;
    }
    if (parsed?.type === 'control' && parsed.session_key === context.sessionKey) {
      void handleControlCommand(parsed.command, context.repoRoot);
    }
  });
  bridgeSocket.addEventListener('close', () => {
    bridgeSocket = null;
    scheduleReconnect(context.repoRoot);
  });
  bridgeSocket.addEventListener('error', () => {});
}

async function drainBridgeQueue(timeoutMs = 250) {
  const deadline = Date.now() + timeoutMs;
  while (bridgeQueue.length > 0 && Date.now() < deadline) {
    flushBridgeQueue();
    await new Promise((resolvePromise) => setTimeout(resolvePromise, 10));
  }
}

const tools = [
  {
    name: 'holdpoint_dry_run',
    description: 'Reference Holdpoint control tool that echoes an optional note.',
    skipPermission: true,
    parameters: {
      type: 'object',
      properties: {
        note: { type: 'string', description: 'Optional text to echo back.' },
      },
    },
    handler: async (args) => {
      const note = typeof args?.note === 'string' && args.note.trim() ? args.note.trim() : 'no note';
      return {
        textResultForLlm: 'Holdpoint dry run completed: ' + note,
        resultType: 'success',
      };
    },
  },
];

session = await joinSession({
  tools,
  onPermissionRequest: async (request) => {
    const entry = getOrCreatePendingEntry(request);
    await ensureBridgeConnection(sessionContext?.repoRoot ?? process.cwd());
    return await new Promise((resolvePromise) => {
      entry.waiting = resolvePromise;
      setTimeout(() => {
        if (entry.waiting === resolvePromise) {
          entry.waiting = null;
          resolvePromise({ kind: 'no-result' });
        }
      }, PERMISSION_TIMEOUT_MS);
    });
  },
  hooks: {
    onSessionStart: async (input) => {
      const context = ensureSessionContext(input.cwd);
      emitEvent(
        createEvent(
          'session_start',
          {
            source: input.source === 'resume' ? 'resume' : 'startup',
            tools_available: ['holdpoint_dry_run'],
          },
          context.repoRoot,
          { caps: LIVE_CAPS, ts: toTs(input.timestamp) },
        ),
      );
      await ensureBridgeConnection(context.repoRoot);
      const addendum = readSessionContextAddendum(context.repoRoot);
      if (addendum?.truncated) {
        emitEvent(
          createEvent(
            'meta',
            {
              kind: 'context_truncated',
              original_length: addendum.originalLength,
              emitted_length: addendum.emittedLength,
            },
            context.repoRoot,
          ),
        );
      }
      return addendum ? { additionalContext: addendum.additionalContext } : undefined;
    },
    onSessionEnd: async (input) => {
      const cwd = sessionContext?.repoRoot ?? input.cwd ?? process.cwd();
      for (const entries of [...pendingByKey.values()]) {
        for (const entry of entries) {
          finalizePendingEntry(entry, 'session_ended');
        }
      }
      emitEvent(
        createEvent(
          'session_end',
          {
            reason: input.reason === 'error' ? 'error' : input.reason === 'user_exit' ? 'user' : 'completed',
          },
          cwd,
          { ts: toTs(input.timestamp) },
        ),
      );
      await drainBridgeQueue();
    },
    onUserPromptSubmitted: async (input) => {
      const cwd = ensureSessionContext(input.cwd).repoRoot;
      emitEvent(
        createEvent(
          'prompt_submit',
          {
            prompt: input.prompt,
          },
          cwd,
          { ts: toTs(input.timestamp) },
        ),
      );
      const injected = consumeInjectContext();
      ${
        injectDatetime
          ? `const now = new Date();
      const datetimeLine =
        "Current date and time: " + now.toISOString() + " (UTC)\\n" +
        "Provided by Holdpoint — use this to avoid knowledge-cutoff confusion.";
      const additionalContext = injected ? datetimeLine + "\\n\\n" + injected : datetimeLine;
      return { additionalContext };`
          : `return injected ? { additionalContext: injected } : undefined;`
      }
    },
    onPreToolUse: async (input) => {
      const repoRoot = ensureSessionContext(input.cwd).repoRoot;
      if (input.toolName === 'task_complete') {
        await session.log('Holdpoint: running checks\\u2026', { ephemeral: true });
        emitEvent(createEvent('meta', { kind: 'copilot_task_complete_check_started' }, repoRoot));
        const result = runHoldpointChecks(repoRoot);
        if (!result.ok) {
          emitEvent(
            createEvent(
              'stop_block',
              {
                reason: result.output,
                failing_checks: [],
              },
              repoRoot,
            ),
          );
          await drainBridgeQueue();
          return {
            permissionDecision: 'deny',
            permissionDecisionReason: result.output,
          };
        }
        emitEvent(createEvent('stop_pass', { duration_ms: result.durationMs }, repoRoot));
        await drainBridgeQueue();
        return;
      }

      const additionalContext = consumeInjectContext();
      return additionalContext ? { additionalContext } : undefined;
    },
  },
});

session.on('tool.execution_start', (event) => {
  const cwd = ensureSessionContext(process.cwd()).repoRoot;
  const writeTargets = extractWriteTargets(event.data.toolName, event.data.arguments || {}, cwd);
  toolCalls.set(event.data.toolCallId, {
    toolName: event.data.toolName,
    toolArgs: event.data.arguments || {},
    startedAt: toTs(event.timestamp),
    writeTargets,
  });
  emitEvent(
    createEvent(
      'tool_pre',
      {
        tool_name: event.data.toolName,
        tool_use_id: event.data.toolCallId,
        tool_input: event.data.arguments || {},
        ...(writeTargets ? { write_targets: writeTargets } : {}),
      },
      cwd,
      { ts: toTs(event.timestamp) },
    ),
  );
});

session.on('tool.execution_complete', (event) => {
  const cwd = ensureSessionContext(process.cwd()).repoRoot;
  const current = toolCalls.get(event.data.toolCallId);
  const durationMs = Math.max(0, toTs(event.timestamp) - (current?.startedAt || toTs(event.timestamp)));
  const writeTargets = current?.writeTargets;
  if (event.data.success) {
    emitEvent(
      createEvent(
        'tool_post',
        {
          tool_name: current?.toolName || 'unknown',
          tool_use_id: event.data.toolCallId,
          success: true,
          duration_ms: durationMs,
          ...(writeTargets ? { write_targets: writeTargets } : {}),
        },
        cwd,
        { ts: toTs(event.timestamp) },
      ),
    );
  } else {
    emitEvent(
      createEvent(
        'tool_failure',
        {
          tool_name: current?.toolName || 'unknown',
          tool_use_id: event.data.toolCallId,
          error: event.data.error?.message || 'Tool execution failed',
        },
        cwd,
        { ts: toTs(event.timestamp) },
      ),
    );
  }
  toolCalls.delete(event.data.toolCallId);
});

session.on('permission.requested', (event) => {
  if (event.data.resolvedByHook) {
    emitEvent(
      createEvent(
        'permission_resolved',
        {
          request_id: event.data.requestId,
          outcome: 'resolved_by_hook',
        },
        sessionContext?.repoRoot ?? process.cwd(),
        { ts: toTs(event.timestamp) },
      ),
    );
    return;
  }

  const entry = getOrCreatePendingEntry(event.data.permissionRequest);
  entry.requestId = event.data.requestId;
  entry.toolCallId = entry.toolCallId || event.data.toolCallId;
  entry.toolName = entry.toolName || (entry.toolCallId ? toolCalls.get(entry.toolCallId)?.toolName : undefined);
  const description = describePermissionRequest(event.data.permissionRequest, entry.toolName);
  entry.title = description.title;
  entry.details = description.details;
  pendingByRequestId.set(event.data.requestId, entry);
  emitEvent(
    createEvent(
      'permission_pending',
      {
        request_id: event.data.requestId,
        permission_kind: event.data.permissionRequest.kind,
        ...(entry.toolCallId ? { tool_call_id: entry.toolCallId } : {}),
        ...(entry.toolName ? { tool_name: entry.toolName } : {}),
        ...(entry.title ? { title: entry.title } : {}),
        ...(entry.details ? { details: entry.details } : {}),
      },
      sessionContext?.repoRoot ?? process.cwd(),
      { ts: toTs(event.timestamp) },
    ),
  );
});

session.on('permission.completed', (event) => {
  const entry = pendingByRequestId.get(event.data.requestId);
  if (!entry) return;
  switch (event.data.result.kind) {
    case 'approved':
    case 'approved-for-session':
    case 'approved-for-location':
      finalizePendingEntry(entry, 'approved');
      break;
    default:
      finalizePendingEntry(entry, 'denied');
      break;
  }
});
`;
}
