import type { HoldpointConfig } from "@holdpoint/types";

/**
 * Generate the .github/hooks/holdpoint.json content for the Copilot CLI hooks system.
 *
 * Always installs a preToolUse hook (matcher: task_complete) to gate task completion.
 * Also installs a sessionStart hook when session_context_files are configured, to
 * inject those files as additionalContext at the start of every session.
 */
export function buildHookJson(config?: HoldpointConfig): string {
  const hooks: Record<string, unknown> = {};

  if (config?.session_context_files?.length) {
    hooks.sessionStart = [
      {
        type: "command",
        bash: "node .github/hooks/holdpoint-check.mjs",
        powershell: "node .github/hooks/holdpoint-check.mjs",
        cwd: ".",
        timeoutSec: 30,
      },
    ];
  }

  hooks.preToolUse = [
    {
      type: "command",
      matcher: "task_complete",
      bash: "node .github/hooks/holdpoint-check.mjs",
      powershell: "node .github/hooks/holdpoint-check.mjs",
      cwd: ".",
      timeoutSec: 180,
    },
  ];

  return (
    JSON.stringify(
      {
        "//": "AUTO-GENERATED by @holdpoint/engine-copilot — do not edit manually.",
        version: 1,
        hooks,
      },
      null,
      2,
    ) + "\n"
  );
}

/**
 * Generate the .github/hooks/holdpoint-check.mjs helper script.
 *
 * Handles two hook events:
 *   - sessionStart: reads session_context_files from checks.immutable.json and
 *     outputs them as additionalContext for the agent (fail-soft — never blocks session).
 *   - preToolUse (task_complete): runs all configured checks and outputs a deny
 *     decision if any fail (fail-closed — blocks task completion on error).
 */
// eslint-disable-next-line @typescript-eslint/no-unused-vars
export function buildCheckScript(_config?: HoldpointConfig): string {
  return `#!/usr/bin/env node
// AUTO-GENERATED by @holdpoint/engine-copilot — do not edit manually.
// Handles: sessionStart (context injection) and preToolUse/task_complete (check gating).

import { execSync } from "node:child_process";
import { existsSync, readFileSync } from "node:fs";
import { join, resolve, sep } from "node:path";

function denyTaskComplete(reason) {
  process.stdout.write(JSON.stringify({ permissionDecision: "deny", permissionDecisionReason: reason }));
  process.exit(0);
}

function resolveRepoRoot(cwd) {
  try {
    return execSync("git rev-parse --show-toplevel", {
      encoding: "utf8",
      stdio: ["pipe", "pipe", "ignore"],
      cwd: cwd ?? process.cwd(),
    }).trim();
  } catch {
    return cwd ?? process.cwd();
  }
}

// ── Parse stdin ───────────────────────────────────────────────────────────────

let input = {};
try {
  const raw = readFileSync(0 /* stdin fd */, "utf8").trim();
  if (raw) input = JSON.parse(raw);
} catch { /* non-JSON or empty stdin — treat as preToolUse */ }

const isSessionStart =
  typeof input.source === "string" &&
  ["startup", "resume", "new"].includes(input.source) &&
  !("toolName" in input) &&
  !("tool_name" in input);

const repoRoot = resolveRepoRoot(input.cwd);

// ── sessionStart: inject context files (fail-soft) ───────────────────────────

if (isSessionStart) {
  try {
    const configPath = join(repoRoot, ".github/holdpoint/generated/checks.immutable.json");
    if (!existsSync(configPath)) {
      process.stderr.write("[holdpoint] checks.immutable.json not found — skipping context injection\\n");
      process.exit(0);
    }
    const config = JSON.parse(readFileSync(configPath, "utf8"));
    const files = Array.isArray(config.session_context_files) ? config.session_context_files : [];
    const parts = [];
    for (const file of files) {
      if (typeof file !== "string" || !file.trim()) continue;
      const abs = resolve(repoRoot, file);
      if (!abs.startsWith(repoRoot + sep) && abs !== repoRoot) {
        process.stderr.write(\`[holdpoint] Skipping unsafe session_context_file path: \${file}\\n\`);
        continue;
      }
      if (!existsSync(abs)) {
        process.stderr.write(\`[holdpoint] session_context_file not found (skipping): \${file}\\n\`);
        continue;
      }
      try {
        parts.push(\`<!-- \${file} -->\\n\${readFileSync(abs, "utf8")}\`);
      } catch (e) {
        process.stderr.write(\`[holdpoint] Failed to read session_context_file \${file}: \${e.message}\\n\`);
      }
    }
    if (parts.length > 0) {
      process.stdout.write(JSON.stringify({ additionalContext: parts.join("\\n\\n") }));
    }
  } catch (err) {
    process.stderr.write(\`[holdpoint] sessionStart hook error: \${err instanceof Error ? err.message : String(err)}\\n\`);
  }
  process.exit(0);
}

// ── preToolUse: run checks before task_complete (fail-closed) ────────────────

// Belt-and-suspenders guard — the matcher in holdpoint.json already limits this to task_complete
const toolName = input.toolName ?? input.tool_name ?? "";
if (toolName && toolName !== "task_complete") {
  process.exit(0);
}

try {
  function getStagedFiles() {
    try {
      return execSync("git diff --cached --name-only", {
        encoding: "utf8",
        stdio: ["pipe", "pipe", "ignore"],
        cwd: repoRoot,
      })
        .trim()
        .split("\\n")
        .filter(Boolean);
    } catch {
      return [];
    }
  }

  function matchesWhen(when, changedFiles, userPatterns) {
    if (!when) return true;
    if (changedFiles.includes("__all__") || changedFiles.length === 0) return true;
    const patterns = {
      frontend: [
        /\\.(tsx|jsx|css|scss)$/,
        /tailwind\\.config\\./,
        /postcss\\.config\\./,
        /^apps\\/(builder|web)\\//,
      ],
      backend: [
        /(^|\\/)api\\//,
        /(^|\\/)server\\//,
        /(^|\\/)routes\\//,
        /(^|\\/)controllers\\//,
        /(^|\\/)middleware\\//,
        /^packages\\/[^/]+\\/src\\//,
      ],
      prisma: [/\\.prisma$/, /(^|\\/)prisma\\//],
      socket: [/(^|\\/)socket\\//, /(^|\\/)ws\\//, /(^|\\/)websocket\\//],
      visual: [/\\.stories\\.(tsx?|jsx?)$/, /(^|\\/)__screenshots__\\//, /\\.snap$/],
      python: [
        /\\.pyi?$/,
        /requirements[^/]*\\.txt$/,
        /pyproject\\.toml$/,
        /setup\\.(py|cfg)$/,
        /(^|\\/)Pipfile(\\.lock)?$/,
        /uv\\.lock$/,
        /pytest\\.ini$/,
        /tox\\.ini$/,
      ],
      go: [/\\.go$/, /go\\.(mod|sum)$/],
      rust: [/\\.rs$/, /Cargo\\.(toml|lock)$/],
      java: [/\\.(java|kt)$/, /\\.gradle(\\.kts)?$/, /pom\\.xml$/],
      ruby: [/\\.rb$/, /(^|\\/)Gemfile(\\.lock)?$/, /(^|\\/)Rakefile$/],
      database: [
        /\\.sql$/,
        /(^|\\/)(migrations?|migration)\\//,
        /(^|\\/)prisma\\//,
        /\\.prisma$/,
        /(^|\\/)db\\//,
        /(^|\\/)database\\//,
        /(^|\\/)(seeds?|seed)\\//,
        /alembic\\.ini$/,
      ],
      testing: [
        /\\.(test|spec)\\.(tsx?|jsx?|py|rb|go)$/,
        /(^|\\/)__tests__\\//,
        /(^|\\/)tests?\\//,
        /(^|\\/)spec\\//,
      ],
      infra: [
        /(^|\\/)Dockerfile(\\..*)?$/,
        /(^|\\/)docker-compose/,
        /\\.(tf|tfvars|hcl)$/,
        /(^|\\/)k8s\\//,
        /(^|\\/)kubernetes\\//,
        /(^|\\/)(helm|charts)\\//,
        /\\.dockerignore$/,
      ],
      ci: [
        /(^|\\/)(\\.github\\/workflows|\\.circleci)\\//,
        /(^|\\/)Jenkinsfile$/,
        /(^|\\/)\\.(gitlab-ci|travis|drone)\\.yml$/,
      ],
      docs: [/\\.(mdx|rst)$/, /(^|\\/)(docs|documentation)\\//],
      structural: [
        /(^|\\/|\\\\)package\\.json$/,
        /tsconfig[^/]*\\.json$/,
        /requirements[^/]*\\.txt$/,
        /pyproject\\.toml$/,
        /(^|\\/)Pipfile(\\.lock)?$/,
        /setup\\.(py|cfg)$/,
        /pytest\\.ini$/,
        /tox\\.ini$/,
        /go\\.mod$/,
        /Cargo\\.toml$/,
        /pom\\.xml$/,
        /build\\.gradle(\\.kts)?$/,
        /(^|\\/)Gemfile(\\.lock)?$/,
        /vitest\\.config\\./,
        /jest\\.config\\./,
        /playwright\\.config\\./,
        /eslint\\.config\\./,
        /\\.eslintrc/,
        /biome\\.json$/,
        /prettier\\.config\\./,
        /\\.prettierrc/,
        /next\\.config\\./,
        /(^|\\/)Dockerfile/,
        /(^|\\/)docker-compose[^/]*\\.(yml|yaml)$/,
        /\\.tf$/,
        /prisma\\/schema\\.prisma$/,
        /openapi\\.(yaml|yml|json)$/,
        /\\.github\\/workflows\\/[^/]+\\.(yml|yaml)$/,
        /(^|\\/)(\\.circleci\\/|Jenkinsfile$|\\.gitlab-ci\\.yml$|\\.travis\\.yml$)/,
      ],
    };
    if (when in patterns) {
      return changedFiles.some((f) => (patterns[when] ?? []).some((re) => re.test(f)));
    }
    // User-defined named patterns
    if (userPatterns && when in userPatterns) {
      return changedFiles.some((f) => new RegExp(userPatterns[when]).test(f));
    }
    return changedFiles.some((f) => new RegExp(when).test(f));
  }

  function runCheck(check) {
    if (!check.cmd) return { status: "pending" };
    try {
      const output = execSync(check.cmd, {
        encoding: "utf8",
        timeout: 60000,
        stdio: "pipe",
        cwd: repoRoot,
      });
      return { status: "pass", output };
    } catch (e) {
      return {
        status: "fail",
        output: [e.stdout, e.stderr].filter(Boolean).join("\\n"),
        exitCode: e.status ?? 1,
      };
    }
  }

  const changedFiles = getStagedFiles();

  // Re-sync if checks.yaml is staged
  if (changedFiles.some((f) => /^checks\\.yaml$/.test(f))) {
    const sync = runCheck({ label: "Holdpoint sync", cmd: "npx holdpoint update" });
    if (sync.status === "fail") {
      denyTaskComplete(
        \`Holdpoint: checks.yaml changed but \\\`holdpoint update\\\` failed:\\n\\n\${(sync.output ?? "").trim()}\\n\\nFix the error above, then retry.\`,
      );
    }
  }

  const configPath = join(repoRoot, ".github/holdpoint/generated/checks.immutable.json");
  if (!existsSync(configPath)) {
    denyTaskComplete("Holdpoint: .github/holdpoint/generated/checks.immutable.json not found — run: npx holdpoint update");
  }

  const config = JSON.parse(readFileSync(configPath, "utf8"));
  const failures = [];

  for (const check of config.checks.filter((c) => c.cmd !== undefined)) {
    if (!matchesWhen(check.when, changedFiles, config.patterns)) continue;
    const result = runCheck(check);
    if (result.status === "fail") failures.push({ check, result });
  }

  // Collect prompt checks so they can be included alongside cmd failures
  const promptChecks = config.checks.filter(
    (c) => c.prompt !== undefined && matchesWhen(c.when, changedFiles, config.patterns),
  );

  if (failures.length > 0) {
    const summary = failures
      .map((f) => \`  ✗ [\${f.check.label}]\\n\${(f.result.output ?? "").trim()}\`)
      .join("\\n\\n");
    const promptSection =
      promptChecks.length > 0
        ? \`\\n\\nComplete these actions before committing:\\n\${promptChecks.map((c) => \`  □ [\${c.label}] \${c.prompt ?? ""}\`).join("\\n")}\`
        : "";
    denyTaskComplete(
      \`Holdpoint: \${failures.length} check(s) failed:\\n\\n\${summary}\${promptSection}\\n\\nFix the above issues before marking the task complete.\`,
    );
  }

  if (promptChecks.length > 0) {
    const list = promptChecks.map((c) => \`  □ [\${c.label}] \${c.prompt ?? ""}\`).join("\\n");
    process.stderr.write(\`[holdpoint] Agent prompts to act on:\\n\${list}\\n\`);
  }

  // Allow — empty stdout = default allow
  process.exit(0);
} catch (err) {
  // Fail-closed: unexpected errors block task completion
  denyTaskComplete(\`Holdpoint hook error: \${err instanceof Error ? err.message : String(err)}\`);
}
`;
}

/** Serialise a HoldpointConfig to checks.immutable.json at .github/holdpoint/generated/. */
export function buildConfigJson(config: HoldpointConfig): string {
  const withHeader: Record<string, unknown> = {
    "//": "AUTO-GENERATED — do not edit this file. Source of truth: checks.yaml. Regenerate: npx holdpoint update",
    ...(config as unknown as Record<string, unknown>),
  };
  return JSON.stringify(withHeader, null, 2) + "\n";
}
