import type { HoldpointConfig } from "@holdpoint/types";

/**
 * Generate the .github/hooks/holdpoint.json content for the Copilot CLI hooks system.
 *
 * Only installs a sessionStart hook when session_context_files are configured, to
 * inject those files as additionalContext at the start of every session.
 * task_complete interception is handled by the SDK extension (extension.mjs), not hooks.
 */
export function buildHookJson(config?: HoldpointConfig): string {
  const hooks: Record<string, unknown> = {};

  if (config?.session_context_files?.length) {
    hooks.sessionStart = [
      {
        type: "command",
        bash: "node .github/hooks/holdpoint-check.mjs",
        powershell: "node .github/hooks/holdpoint-check.mjs",
        cwd: ".",
        timeoutSec: 30,
      },
    ];
  }

  // preToolUse with matcher:task_complete is NOT used here — the local Copilot CLI does
  // not fire preToolUse hooks for internal agent tools like task_complete. That interception
  // is handled by the SDK extension at .github/extensions/holdpoint/extension.mjs instead.

  const hasHooks = Object.keys(hooks).length > 0;
  const obj: Record<string, unknown> = {
    "//": "AUTO-GENERATED by @holdpoint/engine-copilot — do not edit manually.",
    version: 1,
    hooks,
  };
  if (!hasHooks) {
    obj["//2"] =
      "hooks is intentionally empty: task_complete interception runs via extension.mjs. Add session_context_files to checks.yaml to enable a sessionStart hook here.";
  }
  return JSON.stringify(obj, null, 2) + "\n";
}

/**
 * Generate the .github/hooks/holdpoint-check.mjs helper script.
 *
 * Handles the sessionStart hook event only: reads session_context_files from
 * checks.immutable.json and outputs them as additionalContext for the agent
 * (fail-soft — never blocks session start).
 *
 * task_complete interception is handled exclusively by extension.mjs via the
 * Copilot SDK. This script is never invoked for that purpose.
 */
// eslint-disable-next-line @typescript-eslint/no-unused-vars
export function buildCheckScript(_config?: HoldpointConfig): string {
  return `#!/usr/bin/env node
// AUTO-GENERATED by @holdpoint/engine-copilot — do not edit manually.
// sessionStart hook: injects session_context_files as additionalContext.
// task_complete interception is handled by extension.mjs, not this script.

import { execSync } from "node:child_process";
import { existsSync, readFileSync } from "node:fs";
import { join, resolve, sep } from "node:path";

function resolveRepoRoot(cwd) {
  try {
    return execSync("git rev-parse --show-toplevel", {
      encoding: "utf8",
      stdio: ["pipe", "pipe", "ignore"],
      cwd: cwd ?? process.cwd(),
    }).trim();
  } catch {
    return cwd ?? process.cwd();
  }
}

let input = {};
try {
  const raw = readFileSync(0 /* stdin fd */, "utf8").trim();
  if (raw) input = JSON.parse(raw);
} catch { /* non-JSON or empty stdin */ }

const repoRoot = resolveRepoRoot(input.cwd);

try {
  const configPath = join(repoRoot, ".github/holdpoint/generated/checks.immutable.json");
  if (!existsSync(configPath)) {
    process.stderr.write("[holdpoint] checks.immutable.json not found — skipping context injection\\n");
    process.exit(0);
  }
  const config = JSON.parse(readFileSync(configPath, "utf8"));
  const files = Array.isArray(config.session_context_files) ? config.session_context_files : [];
  const parts = [];
  for (const file of files) {
    if (typeof file !== "string" || !file.trim()) continue;
    const abs = resolve(repoRoot, file);
    if (!abs.startsWith(repoRoot + sep) && abs !== repoRoot) {
      process.stderr.write(\`[holdpoint] Skipping unsafe path: \${file}\\n\`);
      continue;
    }
    if (!existsSync(abs)) {
      process.stderr.write(\`[holdpoint] session_context_file not found (skipping): \${file}\\n\`);
      continue;
    }
    try {
      parts.push(\`<!-- \${file} -->\\n\${readFileSync(abs, "utf8")}\`);
    } catch (e) {
      process.stderr.write(\`[holdpoint] Failed to read \${file}: \${e.message}\\n\`);
    }
  }
  if (parts.length > 0) {
    process.stdout.write(JSON.stringify({ additionalContext: parts.join("\\n\\n") }));
  }
} catch (err) {
  process.stderr.write(\`[holdpoint] sessionStart hook error: \${err instanceof Error ? err.message : String(err)}\\n\`);
}
process.exit(0);
`;
}

/** Serialise a HoldpointConfig to checks.immutable.json at .github/holdpoint/generated/. */
export function buildConfigJson(config: HoldpointConfig): string {
  const withHeader: Record<string, unknown> = {
    "//": "AUTO-GENERATED — do not edit this file. Source of truth: checks.yaml. Regenerate: npx holdpoint update",
    ...(config as unknown as Record<string, unknown>),
  };
  return JSON.stringify(withHeader, null, 2) + "\n";
}

/**
 * Generate .github/extensions/holdpoint/extension.mjs for the Copilot CLI local agent.
 *
 * Uses the @github/copilot-sdk/extension API (injected at runtime by the CLI — no install
 * needed). joinSession + onPreToolUse intercepts task_complete before it fires.
 *
 * The extension delegates all check logic to the holdpoint CLI rather than inlining it.
 * This keeps the extension lean, eliminates duplication of when: patterns and check-running
 * logic, and means scope changes in yaml-core are automatically picked up without re-running
 * holdpoint update.
 *
 * The command defaults to `npx holdpoint@alpha check --staged`. Set
 * `engines.copilot.check_command` in checks.yaml to override — useful when holdpoint is
 * installed as a workspace devDep and the local bin should be used instead.
 */
export function buildEngine(config?: HoldpointConfig): string {
  const checkCommand =
    config?.engines?.copilot?.check_command ?? "npx holdpoint@alpha check --staged";
  return `// AUTO-GENERATED by @holdpoint/engine-copilot — do not edit manually.

import { joinSession } from '@github/copilot-sdk/extension';
import { execSync } from 'node:child_process';

function resolveRepoRoot(cwd) {
  try {
    return execSync('git rev-parse --show-toplevel', {
      encoding: 'utf8',
      stdio: ['pipe', 'pipe', 'ignore'],
      cwd: cwd ?? process.cwd(),
    }).trim();
  } catch {
    return cwd ?? process.cwd();
  }
}

const session = await joinSession({
  hooks: {
    onPreToolUse: async (input) => {
      if (input.toolName !== 'task_complete') return;
      const repoRoot = resolveRepoRoot(input.cwd);
      await session.log('Holdpoint: running checks\\u2026', { ephemeral: true });
      try {
        execSync(${JSON.stringify(checkCommand)}, {
          cwd: repoRoot,
          stdio: 'pipe',
          encoding: 'utf8',
        });
      } catch (e) {
        const output = [e.stdout, e.stderr].filter(Boolean).join('\\n').trim();
        return {
          permissionDecision: 'deny',
          permissionDecisionReason: output || 'Holdpoint checks failed. Fix the issues above, then re-attempt.',
        };
      }
    },
  },
});
`;
}
