import type { HoldpointConfig } from "@holdpoint/types";

export const HOLDPOINT_CURSOR_HOOK_MARKER = "HOLDPOINT_MANAGED=cursor";

const HOOK_COMMAND = `node .cursor/holdpoint-hook.mjs # ${HOLDPOINT_CURSOR_HOOK_MARKER}`;

interface CursorHook {
  command: string;
  timeout?: number;
  matcher?: string;
  loop_limit?: number;
  failClosed?: boolean;
}

interface CursorHooksJson {
  version: 1;
  hooks: Record<string, CursorHook[]>;
}

function hook(options: Omit<CursorHook, "command"> = {}): CursorHook {
  return {
    command: HOOK_COMMAND,
    ...options,
  };
}

/**
 * Generate project-level Cursor hooks.
 *
 * Cursor project hooks live at `.cursor/hooks.json`, run from the project root,
 * and can observe, inject context, or auto-continue the agent loop. Holdpoint
 * uses a single generated script so hook behavior stays in sync with
 * `checks.yaml` after every `holdpoint update`.
 */
export function buildHooksJson(config: HoldpointConfig): string {
  const hooks: CursorHooksJson["hooks"] = {
    beforeSubmitPrompt: [hook({ timeout: 30 })],
    preToolUse: [hook({ timeout: 30, matcher: "Shell|Read|Write|Grep|Task|MCP:.*" })],
    postToolUse: [hook({ timeout: 30 })],
    postToolUseFailure: [hook({ timeout: 30 })],
    beforeShellExecution: [hook({ timeout: 30 })],
    afterShellExecution: [hook({ timeout: 30 })],
    beforeMCPExecution: [hook({ timeout: 30 })],
    afterMCPExecution: [hook({ timeout: 30 })],
    beforeReadFile: [hook({ timeout: 30 })],
    afterFileEdit: [hook({ timeout: 30 })],
    subagentStart: [hook({ timeout: 30 })],
    subagentStop: [hook({ timeout: 600, loop_limit: 5 })],
    preCompact: [hook({ timeout: 30 })],
    afterAgentResponse: [hook({ timeout: 30 })],
    stop: [hook({ timeout: 600, loop_limit: 5 })],
  };

  if (config.session_context_files?.length) {
    hooks.sessionStart = [hook({ timeout: 30 })];
  }

  return JSON.stringify({ version: 1, hooks }, null, 2) + "\n";
}

/**
 * Generate `.cursor/holdpoint-hook.mjs`.
 *
 * The script speaks Cursor's native hook protocol:
 * - `sessionStart` returns `additional_context` when session_context_files exist.
 * - `stop` and completed `subagentStop` run Holdpoint checks and return a
 *   `followup_message` on failure so Cursor keeps iterating.
 * - all other hooks are used for Live telemetry and emit either an allow
 *   response or no output, depending on that hook's schema.
 */
export function buildCheckScript(): string {
  return `#!/usr/bin/env node
// AUTO-GENERATED by Holdpoint — do not edit. Re-generate: npx holdpoint update
import { execSync } from "node:child_process";
import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { isAbsolute, join, relative, resolve } from "node:path";

const CHECK_COMMAND = "node_modules/.bin/holdpoint check --staged";
const LIVE_COMMAND = "node_modules/.bin/holdpoint event --engine cursor --from-hook";
const MAX_CONTEXT_CHARS = 100_000;
const MAX_CHECK_OUTPUT_CHARS = 60_000;
const CHECK_MAX_BUFFER_BYTES = 1024 * 1024 * 10;

function readInput() {
  try {
    const raw = readFileSync(0, "utf8").trim();
    return raw ? JSON.parse(raw) : {};
  } catch {
    return {};
  }
}

function resolveRepoRoot(cwd = process.cwd()) {
  try {
    return execSync("git rev-parse --show-toplevel", {
      cwd,
      encoding: "utf8",
      stdio: ["pipe", "pipe", "ignore"],
    }).trim();
  } catch {
    return cwd;
  }
}

function eventName(input) {
  return String(input && input.hook_event_name ? input.hook_event_name : "");
}

function truncateText(value, maxChars) {
  const text = String(value || "");
  if (text.length <= maxChars) return { text, truncated: false, originalLength: text.length };
  return {
    text: text.slice(0, maxChars) + "\\n\\n[Holdpoint output truncated to " + maxChars + " chars.]",
    truncated: true,
    originalLength: text.length,
  };
}

function isPathInsideRoot(repoRoot, absPath) {
  const rel = relative(repoRoot, absPath);
  return rel === "" || (!rel.startsWith("..") && !isAbsolute(rel));
}

function sendLiveEvent(input) {
  try {
    execSync(LIVE_COMMAND, {
      input: JSON.stringify(input),
      encoding: "utf8",
      stdio: ["pipe", "ignore", "ignore"],
    });
  } catch {
    // Live telemetry is best-effort and must never break Cursor's hook flow.
  }
}

function readSessionContext(repoRoot) {
  const configPath = join(repoRoot, ".github/holdpoint/generated/checks.immutable.json");
  if (!existsSync(configPath)) return undefined;
  try {
    const config = JSON.parse(readFileSync(configPath, "utf8"));
    const files = Array.isArray(config.session_context_files) ? config.session_context_files : [];
    const parts = [];
    for (const file of files) {
      if (typeof file !== "string" || !file.trim()) continue;
      const abs = resolve(repoRoot, file);
      if (!isPathInsideRoot(repoRoot, abs) || !existsSync(abs)) continue;
      try {
        parts.push("<!-- " + file + " -->\\n" + readFileSync(abs, "utf8"));
      } catch {}
    }
    if (parts.length === 0) return undefined;
    const context = truncateText(parts.join("\\n\\n"), MAX_CONTEXT_CHARS);
    return {
      additional_context: context.text,
      truncated: context.truncated,
      originalLength: context.originalLength,
      emittedLength: context.text.length,
    };
  } catch {
    return undefined;
  }
}

function runHoldpointChecks(repoRoot) {
  const startedAt = Date.now();
  try {
    const output = execSync(CHECK_COMMAND, {
      cwd: repoRoot,
      stdio: "pipe",
      encoding: "utf8",
      maxBuffer: CHECK_MAX_BUFFER_BYTES,
    });
    return {
      ok: true,
      durationMs: Date.now() - startedAt,
      output: String(output || "").trim(),
    };
  } catch (error) {
    const output = [error && error.stdout, error && error.stderr, error && error.message]
      .filter(Boolean)
      .join("\\n")
      .trim();
    const truncated = truncateText(output, MAX_CHECK_OUTPUT_CHARS);
    return {
      ok: false,
      durationMs: Date.now() - startedAt,
      output: truncated.text || "Holdpoint checks failed. Fix the issues above, then re-attempt.",
      truncated: truncated.truncated,
      originalLength: truncated.originalLength,
    };
  }
}

function shouldRunCompletionChecks(input) {
  const name = eventName(input);
  if (name === "stop") return true;
  if (name === "subagentStop") {
    return input && input.status === "completed";
  }
  return false;
}

const input = readInput();
const cwd = typeof input.cwd === "string" ? input.cwd : process.cwd();
const repoRoot = resolveRepoRoot(cwd);
const name = eventName(input);

if (name === "sessionStart") {
  const context = readSessionContext(repoRoot);
  sendLiveEvent({
    ...input,
    holdpoint_context: context
      ? {
          truncated: context.truncated,
          originalLength: context.originalLength,
          emittedLength: context.emittedLength,
        }
      : undefined,
  });
  if (context?.additional_context) {
    writeFileSync(1, JSON.stringify({ additional_context: context.additional_context }) + "\\n");
  }
  process.exit(0);
}

if (shouldRunCompletionChecks(input)) {
  const result = runHoldpointChecks(repoRoot);
  sendLiveEvent({ ...input, holdpoint_check: result });
  if (result.ok) {
    process.exit(0);
  }
  process.stdout.write(
    JSON.stringify({
      followup_message:
        result.output +
        "\\n\\nHoldpoint checks failed. Fix the issues above, then run the checks again before finishing.",
    }) + "\\n",
  );
  process.exit(0);
}

sendLiveEvent(input);

if (
  name === "preToolUse" ||
  name === "beforeShellExecution" ||
  name === "beforeMCPExecution" ||
  name === "beforeReadFile" ||
  name === "subagentStart"
) {
  process.stdout.write(JSON.stringify({ permission: "allow" }) + "\\n");
} else if (name === "beforeSubmitPrompt") {
  process.stdout.write(JSON.stringify({ continue: true }) + "\\n");
}
process.exit(0);
`;
}

/**
 * Generate a standalone context-injection script for sessionStart tests.
 * Cursor uses the same generated dispatcher for context, telemetry, and gates.
 */
export function buildContextScript(): string {
  return buildCheckScript();
}

/**
 * Generate .cursorrules additions from a HoldpointConfig.
 *
 * Cursor now enforces Holdpoint through `.cursor/hooks.json`; this rules block
 * remains useful context for the agent and for Cursor cloud cases where not all
 * local hook stages are available.
 */
export function buildEngine(config: HoldpointConfig): string {
  const deterministicList = config.checks
    .filter((c) => c.cmd !== undefined)
    .map((c) => `  - [${c.when ?? "always"}] ${c.label}: \`${c.cmd ?? "(no cmd)"}\``)
    .join("\n");

  const promptList = config.checks
    .filter((c) => c.prompt !== undefined)
    .map((c) => `  - [${c.when ?? "always"}] ${c.label}: ${c.prompt ?? ""}`)
    .join("\n");

  return `# ─── Holdpoint Rules (auto-generated) ─────────────────────────────────────────
# DO NOT EDIT this block manually. Re-generate with: npx holdpoint update

## Mandatory pre-completion checks

Holdpoint also installed Cursor project hooks in \`.cursor/hooks.json\`. Before
marking ANY task as done or making a final commit, you MUST:

1. Run all Holdpoint tasks and confirm they pass:
${deterministicList || "  (no tasks configured)"}

2. Act on all matching agent prompts:
${promptList || "  (no prompt checks configured)"}

3. If any task exits non-zero, fix the underlying issue before
   proceeding. Do NOT suppress errors or skip tasks.

4. For prompt checks, explicitly state in your response that you have acted on
   each item before marking the task complete.

## Running checks
   Run: \`node_modules/.bin/holdpoint check --staged\` to execute all tasks.
   Fix all failures before proceeding.

# ─── End Holdpoint Rules ───────────────────────────────────────────────────────
`;
}
